#!/usr/bin/env python3
"""Compose every face crop into one sprite sheet.

The mosaic draws several hundred faces at once, every frame. As separate
<img>/<image> elements that is hundreds of decodes — an <image> costs its pixel
area times four bytes once decoded, whatever the file weighs, so the mosaic in
that form runs to hundreds of megabytes and the tab is killed. As one sheet it
is a single decode the size of the sheet, and drawing a face is a sub-rectangle
blit, which is the fastest thing a canvas does.

Writes atlas.jpg (the sheet) and atlas.js (which id sits in which cell), both
at the repo root. Both are generated; don't hand-edit either.

The sheet deliberately does NOT live in photos/. fetch_photos.py --manifest
rebuilds photos.js by globbing photos/*.jpg and taking every filename stem as a
person's id, so a sprite sheet parked in there is indexed as a member of the
roster called "atlas" — which it duly was, until this moved.

    python3 build_atlas.py            # 48px cells
    python3 build_atlas.py --cell 64  # bigger, sharper, four times the memory
"""
import argparse, json, math, os, re, sys
from PIL import Image

ROOT = os.path.dirname(os.path.abspath(__file__))
FACES = os.path.join(ROOT, 'photos', 'faces')
FULLS = os.path.join(ROOT, 'photos')


def photo_ids():
    """The manifest's own order, so the atlas and HAS_PHOTO agree on the roster."""
    src = open(os.path.join(ROOT, 'photos.js'), encoding='utf-8').read()
    body = src.split('PHOTO_IDS = [', 1)[1].split(']', 1)[0]
    return re.findall(r"'([^']+)'", body)


def square(path, cell):
    """A face crop is already square; a full portrait is cropped to its upper
    middle, which is where a portrait's subject almost always is."""
    im = Image.open(path).convert('RGB')
    w, h = im.size
    if w != h:
        s = min(w, h)
        left = (w - s) // 2
        top = 0 if h > w else (h - s) // 2
        im = im.crop((left, top, left + s, top + s))
    return im.resize((cell, cell), Image.LANCZOS)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--cell', type=int, default=48)
    ap.add_argument('--quality', type=int, default=82)
    args = ap.parse_args()
    cell = args.cell

    ids, missing = [], 0
    for pid in photo_ids():
        face = os.path.join(FACES, pid + '.jpg')
        full = os.path.join(FULLS, pid + '.jpg')
        path = face if os.path.exists(face) else (full if os.path.exists(full) else None)
        if not path:
            missing += 1
            continue
        ids.append((pid, path))

    n = len(ids)
    cols = math.ceil(math.sqrt(n))
    rows = math.ceil(n / cols)
    sheet = Image.new('RGB', (cols * cell, rows * cell), (12, 15, 22))
    for i, (pid, path) in enumerate(ids):
        try:
            sheet.paste(square(path, cell), ((i % cols) * cell, (i // cols) * cell))
        except Exception as e:
            print('  skip %s: %s' % (pid, e), file=sys.stderr)

    out_img = os.path.join(ROOT, 'atlas.jpg')
    sheet.save(out_img, 'JPEG', quality=args.quality, optimize=True, progressive=True)

    with open(os.path.join(ROOT, 'atlas.js'), 'w', encoding='utf-8') as f:
        f.write('// Generated by build_atlas.py — do not edit by hand.\n')
        f.write('// The mosaic reads this to know which cell of photos/atlas.jpg\n')
        f.write('// holds which person. Cell n sits at (n %% cols, n / cols).\n')
        f.write('export const ATLAS = { src: "./atlas.jpg", cell: %d, cols: %d, rows: %d };\n'
                % (cell, cols, rows))
        f.write('export const ATLAS_IDS = ')
        f.write(json.dumps([pid for pid, _ in ids], indent=0).replace('\n', ''))
        f.write(';\n')
        f.write('export const ATLAS_SLOT = new Map(ATLAS_IDS.map((id, i) => [id, i]));\n')

    kb = os.path.getsize(out_img) / 1024
    print('%d faces  %dx%d cells of %dpx  sheet %dx%d  %.0f KB  (%d decoded MB)'
          % (n, cols, rows, cell, sheet.width, sheet.height, kb,
             sheet.width * sheet.height * 4 / 1e6))
    if missing:
        print('%d ids in photos.js had no file' % missing)


if __name__ == '__main__':
    main()
