// identifiers.js — external keys for the roster, and a title index for adding to it.
//
// Generated, not hand-written. The source is the PolyJamerous Supabase database
// (185,066 music artists, ../Polyjamorous), which carries MusicBrainz IDs and
// Wikipedia URLs that this roster has never had. Nothing here is prose: its bios
// are LLM-written and carry a plagiarism-rewrite queue, so none of them were
// taken. Identifiers only.
//
// NOT imported by app.js. The browser never needs any of this — it exists so the
// maintenance scripts can stop guessing which article a name refers to.
//
// ---------------------------------------------------------------------------
// ROSTER_IDS — keyed by the id in data.js.
//
// Every entry was checked before it was written. An MBID was kept only where
// MusicBrainz agrees the entity is a Person AND its birth year is within a year
// of the one already in data.js; a name match on its own is not an identity, and
// a wrong MBID is worse than none. That check rejected Afric Simone, where
// MusicBrainz says 1956 and the roster says 1939 — one of the two is wrong and
// this is not the pass that decides which. Miles Davis, Peter Tosh, Chavela
// Vargas and Zac Brown are absent only because the lookup rate-limited twice.
//
// Wikipedia titles were checked the same way: the article's opening had to
// mention a year within one of the roster's, and disambiguation pages were
// dropped. All 192 passed.
//
//   mbid   MusicBrainz artist gid — the disambiguation key this roster lacked
//   wiki   exact article title, so fetch_photos.lookup_batch stops guessing
//   gender/area  what MusicBrainz holds; recorded for cross-checking, not truth
// ---------------------------------------------------------------------------
export const ROSTER_IDS = {
  "aaron-copland": {
    "area": "United States",
    "gender": "male",
    "mbid": "aad3af83-5b59-4b86-a569-1a8409149b09",
    "wiki": "Aaron Copland"
  },
  "afric-simone": {
    "wiki": "Afric Simone"
  },
  "alanis-morissette": {
    "wiki": "Alanis Morissette"
  },
  "alice-coltrane": {
    "area": "United States",
    "gender": "female",
    "mbid": "d24fc285-7b2f-47da-8ac5-4070b08570b1",
    "wiki": "Alice Coltrane"
  },
  "amanda-lear": {
    "wiki": "Amanda Lear"
  },
  "amy-winehouse": {
    "wiki": "Amy Winehouse"
  },
  "angelique-kidjo": {
    "area": "Benin",
    "gender": "female",
    "mbid": "80fe34d0-6b4f-4ccd-81c3-281ab37f0451",
    "wiki": "Angélique Kidjo"
  },
  "anita-baker": {
    "wiki": "Anita Baker"
  },
  "annie-lennox": {
    "wiki": "Annie Lennox"
  },
  "antonin-dvorak": {
    "area": "Czechia",
    "gender": "male",
    "mbid": "819eaeb2-8dd8-48a5-ad07-0bcd137985ef",
    "wiki": "Antonin Dvorak"
  },
  "aretha-franklin": {
    "wiki": "Aretha Franklin"
  },
  "ariana-grande": {
    "wiki": "Ariana Grande"
  },
  "arvo-part": {
    "area": "Estonia",
    "gender": "male",
    "mbid": "ae0b2424-d4c5-4c54-82ac-fe3be5453270",
    "wiki": "Arvo Pärt"
  },
  "avril-lavigne": {
    "wiki": "Avril Lavigne"
  },
  "bach": {
    "area": "Germany",
    "gender": "male",
    "mbid": "24f1766e-9635-4d58-a4d4-9413f9f98a4c",
    "wiki": "Johann Sebastian Bach"
  },
  "basshunter": {
    "area": "Sweden",
    "gender": "male",
    "mbid": "255e2420-5b02-452b-9771-0512ebe78090"
  },
  "beethoven": {
    "area": "Germany",
    "gender": "male",
    "mbid": "1f9df192-a621-4f54-8850-2c5373b7eac9",
    "wiki": "Ludwig van Beethoven"
  },
  "belinda-carlisle": {
    "area": "United States",
    "gender": "female",
    "mbid": "2925aac9-5474-4030-b8a3-4151107010b2",
    "wiki": "Belinda Carlisle"
  },
  "bella-poarch": {
    "wiki": "Bella Poarch"
  },
  "bill-evans": {
    "gender": "male",
    "mbid": "a8ed5bd0-15c9-40e4-82a6-9d12aca19c72",
    "wiki": "Bill Evans"
  },
  "billie-eilish": {
    "area": "United States",
    "gender": "female",
    "mbid": "f4abc0b5-3f7a-4eff-8f78-ac078dbce533",
    "wiki": "Billie Eilish"
  },
  "billy-ocean": {
    "area": "United Kingdom",
    "gender": "male",
    "mbid": "0e422e91-a42a-4b4d-8413-9baff67350f2",
    "wiki": "Billy Ocean"
  },
  "billy-strayhorn": {
    "area": "United States",
    "gender": "male",
    "mbid": "23ec9ce1-2dae-437d-ba33-d6ddfe8fd0a9",
    "wiki": "Billy Strayhorn"
  },
  "bjork-2": {
    "area": "Iceland",
    "gender": "female",
    "mbid": "87c5dedd-371d-4a53-9f7f-80522fb7f3cb",
    "wiki": "Björk"
  },
  "bob-marley": {
    "wiki": "Bob Marley"
  },
  "bobi-wine": {
    "area": "Uganda",
    "gender": "male",
    "mbid": "1077d757-4d9f-451a-8f1e-3912110512f1",
    "wiki": "Bobi Wine"
  },
  "britney-spears": {
    "wiki": "Britney Spears"
  },
  "burt-bacharach": {
    "wiki": "Burt Bacharach"
  },
  "caetano-veloso": {
    "area": "Brazil",
    "gender": "male",
    "mbid": "f07dbc2f-317b-470f-bad4-5f1b0eb6faf1",
    "wiki": "Caetano Veloso"
  },
  "camila-cabello": {
    "wiki": "Camila Cabello"
  },
  "cannonball-adderley": {
    "area": "United States",
    "gender": "male",
    "mbid": "a4c73ebe-b2c7-4f13-b99d-2fe1f9f27da8",
    "wiki": "Cannonball Adderley"
  },
  "carly-simon": {
    "wiki": "Carly Simon"
  },
  "carole-king": {
    "wiki": "Carole King"
  },
  "carrie-underwood": {
    "area": "United States",
    "gender": "female",
    "mbid": "70f0e309-5418-49b6-a130-666e2f76eecd",
    "wiki": "Carrie Underwood"
  },
  "celia-cruz": {
    "area": "Cuba",
    "gender": "female",
    "mbid": "7b8e1188-9ca4-4aa5-8393-172de6fa04de",
    "wiki": "Celia Cruz"
  },
  "celine-dion": {
    "wiki": "Celine Dion"
  },
  "charles-mingus": {
    "area": "United States",
    "gender": "male",
    "mbid": "f3b8e107-abe8-4743-b6a3-4a4ee995e71f",
    "wiki": "Charles Mingus"
  },
  "charli-xcx-2": {
    "area": "England",
    "gender": "female",
    "mbid": "260b6184-8828-48eb-945c-bc4cb6fc34ca",
    "wiki": "Charli XCX"
  },
  "charlie-parker": {
    "area": "United States",
    "gender": "male",
    "mbid": "c7356af9-9ea6-4a78-a55b-c73775716312",
    "wiki": "Charlie Parker"
  },
  "chavela-vargas": {
    "wiki": "Chavela Vargas"
  },
  "christina-aguilera": {
    "wiki": "Christina Aguilera"
  },
  "christine-mcvie": {
    "wiki": "Christine McVie"
  },
  "clara-schumann": {
    "area": "Germany",
    "gender": "female",
    "mbid": "36df8e64-6ec6-4342-9045-e962ab9effb3"
  },
  "coltrane": {
    "area": "United States",
    "gender": "male",
    "mbid": "b625448e-bf4a-41c3-a421-72ad46cdb831",
    "wiki": "John Coltrane"
  },
  "compay-segundo": {
    "area": "Cuba",
    "gender": "male",
    "mbid": "8b8ab7a4-add8-4353-a586-e1086e521af8",
    "wiki": "Compay Segundo"
  },
  "corbin-bleu": {
    "wiki": "Corbin Bleu"
  },
  "cyndi-lauper": {
    "area": "United States",
    "gender": "female",
    "mbid": "7bd9e20e-74b9-446a-a2ed-a223f82a36e7",
    "wiki": "Cyndi Lauper"
  },
  "damian-marley": {
    "wiki": "Damian Marley"
  },
  "david-guetta": {
    "area": "France",
    "gender": "male",
    "mbid": "302bd7b9-d012-4360-897a-93b00c855680",
    "wiki": "David Guetta"
  },
  "demi-lovato": {
    "wiki": "Demi Lovato"
  },
  "diana-ross": {
    "area": "United States",
    "gender": "female",
    "mbid": "60d41417-feda-4734-bbbf-7dcc30e08a83",
    "wiki": "Diana Ross"
  },
  "dionne-warwick": {
    "wiki": "Dionne Warwick"
  },
  "dolly-parton": {
    "area": "United States",
    "gender": "female",
    "mbid": "1d543e07-d0d2-4834-a8db-d65c50c2a856",
    "wiki": "Dolly Parton"
  },
  "dorothy-masuka": {
    "area": "South Africa",
    "gender": "female",
    "mbid": "fe47ce05-4fae-4a9c-8592-e4ac701503b1",
    "wiki": "Dorothy Masuka"
  },
  "dua-lipa": {
    "wiki": "Dua Lipa"
  },
  "duncan-laurence": {
    "wiki": "Duncan Laurence"
  },
  "eddy-grant": {
    "area": "United Kingdom",
    "gender": "male",
    "mbid": "0cf0583a-fcfd-4f07-b573-95273ec4bdb5",
    "wiki": "Eddy Grant"
  },
  "edvard-grieg": {
    "area": "Norway",
    "gender": "male",
    "mbid": "013c8e5b-d72a-4cd3-8dee-6c64d6125823",
    "wiki": "Edvard Grieg"
  },
  "ella-fitzgerald": {
    "area": "United States",
    "gender": "female",
    "mbid": "54799c0e-eb45-4eea-996d-c4d71a63c499",
    "wiki": "Ella Fitzgerald"
  },
  "ellie-goulding": {
    "area": "United Kingdom",
    "gender": "female",
    "mbid": "33ca19f4-18c8-4411-98df-ac23890ce9f5",
    "wiki": "Ellie Goulding"
  },
  "emmelie-de-forest": {
    "area": "Denmark",
    "gender": "female",
    "mbid": "7d397268-6447-458f-8da5-a89aa4f451b8",
    "wiki": "Emmelie de Forest"
  },
  "emmylou-harris": {
    "area": "United States",
    "gender": "female",
    "mbid": "35ef61ca-43db-4772-ba27-0489e9ebcb69",
    "wiki": "Emmylou Harris"
  },
  "enrique-iglesias": {
    "wiki": "Enrique Iglesias"
  },
  "enya": {
    "area": "Ireland",
    "gender": "female",
    "mbid": "4967c0a1-b9f3-465e-8440-4598fd9fc33c",
    "wiki": "enya"
  },
  "eric-clapton": {
    "wiki": "Eric Clapton"
  },
  "faith-hill": {
    "area": "United States",
    "gender": "female",
    "mbid": "406552d4-5ba1-4226-b7c0-367bc50fc767",
    "wiki": "Faith Hill"
  },
  "fela-kuti": {
    "area": "Nigeria",
    "gender": "male",
    "mbid": "6514cffa-fbe0-4965-ad88-e998ead8a82a",
    "wiki": "Fela Kuti"
  },
  "fiona-apple": {
    "wiki": "Fiona Apple"
  },
  "florence-ballard": {
    "wiki": "Florence Ballard"
  },
  "florence-welch": {
    "wiki": "Florence Welch"
  },
  "freddie-mercury-2": {
    "wiki": "Freddie Mercury"
  },
  "gal-costa": {
    "area": "Brazil",
    "gender": "female",
    "mbid": "fc63a914-272d-4b95-9221-61adcce6f793",
    "wiki": "Gal Costa"
  },
  "george-harrison": {
    "wiki": "George Harrison"
  },
  "george-michael": {
    "wiki": "George Michael"
  },
  "gilberto-gil": {
    "area": "Brazil",
    "gender": "male",
    "mbid": "cf6b70f6-2616-481c-912c-0263cabfc974",
    "wiki": "Gilberto Gil"
  },
  "gims": {
    "area": "France",
    "gender": "male",
    "mbid": "b2fbd053-4380-412c-95d2-35c6da8f1011"
  },
  "giuseppe-tartini": {
    "area": "Italy",
    "gender": "male",
    "mbid": "90c8118e-b5cc-4df8-80d3-8079879c9cef",
    "wiki": "Giuseppe Tartini"
  },
  "gloria-estefan": {
    "wiki": "Gloria Estefan"
  },
  "goran-bregovic": {
    "wiki": "Goran Bregović"
  },
  "grace-jones": {
    "area": "United States",
    "gender": "female",
    "mbid": "b1c124b3-cf60-41a6-8699-92728c8a3fe0",
    "wiki": "Grace Jones"
  },
  "gustav-mahler": {
    "area": "Austria",
    "gender": "male",
    "mbid": "8d610e51-64b4-4654-b8df-064b0fb7a9d9",
    "wiki": "Gustav Mahler"
  },
  "guy-sebastian": {
    "wiki": "Guy Sebastian"
  },
  "gwen-stefani": {
    "wiki": "Gwen Stefani"
  },
  "haddaway": {
    "area": "Germany",
    "gender": "male",
    "mbid": "6508cf1d-4da2-4d71-81ec-0e072338991f"
  },
  "hande-yener": {
    "area": "Türkiye",
    "gender": "female",
    "mbid": "ebef6120-fbb3-4537-84bc-27902d5760c1"
  },
  "hank-jones": {
    "area": "United States",
    "gender": "male",
    "mbid": "80d610fe-7771-4226-aa9b-950944791698",
    "wiki": "Hank Jones"
  },
  "hank-williams": {
    "area": "United States",
    "gender": "male",
    "mbid": "906bddec-bc73-49f8-ac1e-eaee691c6cf9",
    "wiki": "Hank Williams"
  },
  "harry-styles": {
    "wiki": "Harry Styles"
  },
  "herbie-hancock": {
    "area": "United States",
    "gender": "male",
    "mbid": "27613b78-1b9d-4ec3-9db5-fa0743465fdd",
    "wiki": "Herbie Hancock"
  },
  "hilary-duff": {
    "wiki": "Hilary Duff"
  },
  "hugo-wolf": {
    "area": "Austria",
    "gender": "male",
    "mbid": "21f39bff-fdec-4424-8ad7-86207565d571",
    "wiki": "Hugo Wolf"
  },
  "iggy-azalea-2": {
    "area": "United States",
    "gender": "female",
    "mbid": "3a052c99-8c18-484a-8beb-9873b4fb3106"
  },
  "ishowspeed": {
    "area": "United States",
    "gender": "male",
    "mbid": "d7defc5c-2869-40f0-9d56-2a0292aaeba5",
    "wiki": "IShowSpeed"
  },
  "janelle-monae": {
    "wiki": "Janelle Monáe"
  },
  "janet-jackson": {
    "wiki": "Janet Jackson"
  },
  "jean-sibelius": {
    "area": "Finland",
    "gender": "male",
    "mbid": "691b0e9d-9e57-41cf-932d-a3d21b068e75",
    "wiki": "Jean Sibelius"
  },
  "jennifer-lopez": {
    "wiki": "Jennifer Lopez"
  },
  "jessica-simpson": {
    "wiki": "Jessica Simpson"
  },
  "jimin": {
    "wiki": "Jimin"
  },
  "jimmy-cliff": {
    "area": "Jamaica",
    "gender": "male",
    "mbid": "2caa54a7-b08c-41da-b892-3a41abe778be",
    "wiki": "Jimmy Cliff"
  },
  "jimmy-page": {
    "wiki": "Jimmy Page"
  },
  "joan-jett": {
    "wiki": "Joan Jett"
  },
  "johann-nepomuk-hummel": {
    "area": "Austria",
    "gender": "male",
    "mbid": "f7ef501b-2bc0-4083-ac52-3518255883a2",
    "wiki": "Johann Nepomuk Hummel"
  },
  "john-lennon": {
    "wiki": "John Lennon"
  },
  "johnny-cash": {
    "wiki": "Johnny Cash"
  },
  "joni-mitchell": {
    "wiki": "Joni Mitchell"
  },
  "juan-luis-guerra": {
    "area": "Dominican Republic",
    "gender": "male",
    "mbid": "c3dcad1b-1380-4a94-98d8-3f8272f19df6",
    "wiki": "Juan Luis Guerra"
  },
  "juanes": {
    "wiki": "Juanes"
  },
  "judy-collins": {
    "wiki": "Judy Collins"
  },
  "june-carter-cash": {
    "area": "United States",
    "gender": "female",
    "mbid": "4ee75011-678b-46e0-b8e1-8ef47e5b7379",
    "wiki": "June Carter Cash"
  },
  "k-naan": {
    "wiki": "K'naan"
  },
  "kacey-musgraves": {
    "area": "United States",
    "gender": "female",
    "mbid": "d1393ecb-431b-4fde-a6ea-d769f2f040cb",
    "wiki": "Kacey Musgraves"
  },
  "kanye-west": {
    "wiki": "Kanye West"
  },
  "kate-bush": {
    "wiki": "Kate Bush"
  },
  "keith-richards": {
    "wiki": "Keith Richards"
  },
  "kelly-clarkson": {
    "wiki": "Kelly Clarkson"
  },
  "kylie-minogue": {
    "area": "Australia",
    "gender": "female",
    "mbid": "2fddb92d-24b2-46a5-bf28-3aed46f4684c",
    "wiki": "Kylie Minogue"
  },
  "lady-gaga-2": {
    "area": "United States",
    "gender": "female",
    "mbid": "650e7db6-b795-4eb5-a702-5ea2fc46c848",
    "wiki": "Lady Gaga"
  },
  "lana-del-rey-2": {
    "wiki": "Lana Del Rey"
  },
  "leann-rimes": {
    "area": "United States",
    "gender": "female",
    "mbid": "9092d8e1-9b38-4372-a96d-000b8561a8bc",
    "wiki": "LeAnn Rimes"
  },
  "lena-horne": {
    "area": "United States",
    "gender": "female",
    "mbid": "0031bc7a-1b6f-4620-99db-5202405b0749",
    "wiki": "Lena Horne"
  },
  "leona-lewis": {
    "wiki": "Leona Lewis"
  },
  "leonard-bernstein": {
    "area": "United States",
    "gender": "male",
    "mbid": "fa39bc82-9b27-4bbb-9425-d719a72e09ac",
    "wiki": "Leonard Bernstein"
  },
  "liam-payne": {
    "wiki": "Liam Payne"
  },
  "lila-downs": {
    "area": "Mexico",
    "gender": "female",
    "mbid": "ad29ae1c-2eda-4071-9dc8-31910e7e546c",
    "wiki": "Lila Downs"
  },
  "linda-ronstadt": {
    "wiki": "Linda Ronstadt"
  },
  "lisa-gerrard": {
    "area": "Australia",
    "gender": "female",
    "mbid": "cd645207-1664-46af-9953-264e9ae54089",
    "wiki": "Lisa Gerrard"
  },
  "lorde-2": {
    "area": "New Zealand",
    "gender": "female",
    "mbid": "8e494408-8620-4c6a-82c2-c2ca4a1e4f12",
    "wiki": "Lorde"
  },
  "loreen": {
    "area": "Sweden",
    "gender": "female",
    "mbid": "1e234774-8e37-4378-b01d-b7dd6ced769c",
    "wiki": "Loreen"
  },
  "loretta-lynn": {
    "area": "United States",
    "gender": "female",
    "mbid": "613260c3-d620-4645-94cd-33cd55f29b1e",
    "wiki": "Loretta Lynn"
  },
  "lou-reed": {
    "wiki": "Lou Reed"
  },
  "louis-armstrong": {
    "area": "United States",
    "gender": "male",
    "mbid": "eea8a864-fcda-4602-9569-38ab446decd6",
    "wiki": "Louis Armstrong"
  },
  "mad-professor": {
    "area": "United Kingdom",
    "gender": "male",
    "mbid": "ea3b97e8-8a76-4ea7-8e6f-3ebf40acaeb8",
    "wiki": "Mad Professor"
  },
  "mahalia-jackson": {
    "wiki": "Mahalia Jackson"
  },
  "maluma": {
    "wiki": "Maluma"
  },
  "manu-dibango": {
    "area": "Cameroon",
    "gender": "male",
    "mbid": "826b488f-5164-45ca-abc4-ab11b3c321eb",
    "wiki": "Manu Dibango"
  },
  "mariah-carey": {
    "wiki": "Mariah Carey"
  },
  "marjorie-estiano": {
    "wiki": "Marjorie Estiano"
  },
  "martin-garrix": {
    "area": "Netherlands",
    "gender": "male",
    "mbid": "3e1f2ee4-16be-4406-bf18-6173840cf2b1",
    "wiki": "Martin Garrix"
  },
  "marvin-gaye": {
    "area": "United States",
    "gender": "male",
    "mbid": "afdb7919-059d-43c1-b668-ba1d265e7e42",
    "wiki": "Marvin Gaye"
  },
  "mary-j-blige": {
    "area": "United States",
    "gender": "female",
    "mbid": "db76c5ca-d555-4f09-b1db-baa1b713d875",
    "wiki": "Mary J. Blige"
  },
  "mary-wells": {
    "wiki": "Mary Wells"
  },
  "michael-jackson": {
    "area": "United States",
    "gender": "male",
    "mbid": "f27ec8db-af05-4f36-916e-3d57f91ecf5e",
    "wiki": "Michael Jackson"
  },
  "mick-jagger": {
    "wiki": "Mick Jagger"
  },
  "miguel-bose": {
    "area": "Spain",
    "gender": "male",
    "mbid": "98ad7a28-1949-4786-b1f6-4fa05b9b440c",
    "wiki": "Miguel Bosé"
  },
  "miles-davis": {
    "wiki": "Miles Davis"
  },
  "miley-cyrus": {
    "area": "United States",
    "gender": "non-binary",
    "mbid": "7e9bd05a-117f-4cce-87bc-e011527a8b18",
    "wiki": "Miley Cyrus"
  },
  "mozart": {
    "area": "Austria",
    "gender": "male",
    "mbid": "b972f589-fb0e-474e-b64a-803b0364fa75",
    "wiki": "Wolfgang Amadeus Mozart"
  },
  "natalia-oreiro": {
    "wiki": "Natalia Oreiro"
  },
  "natti-natasha": {
    "wiki": "Natti Natasha"
  },
  "nelly-furtado": {
    "wiki": "Nelly Furtado"
  },
  "nick-drake": {
    "wiki": "Nick Drake"
  },
  "norah-jones": {
    "area": "United States",
    "gender": "female",
    "mbid": "985c709c-7771-4de3-9024-7bda29ebe3f9",
    "wiki": "Norah Jones"
  },
  "olivia-newton-john": {
    "wiki": "Olivia Newton-John"
  },
  "olivia-rodrigo": {
    "wiki": "Olivia Rodrigo"
  },
  "oscar-isaac": {
    "area": "United States",
    "gender": "male",
    "mbid": "f5f3305f-22ea-45d5-a15e-0fbfedc08ccd",
    "wiki": "Oscar Isaac"
  },
  "pat-benatar": {
    "wiki": "Pat Benatar"
  },
  "patti-smith": {
    "wiki": "Patti Smith"
  },
  "paul-mccartney": {
    "wiki": "Paul McCartney"
  },
  "peter-tosh": {
    "wiki": "Peter Tosh"
  },
  "petula-clark": {
    "area": "United Kingdom",
    "gender": "female",
    "mbid": "40e69149-45a7-4dab-8128-c5a4d9654eeb",
    "wiki": "Petula Clark"
  },
  "philip-glass": {
    "area": "United States",
    "gender": "male",
    "mbid": "5ae54dee-4dba-49c0-802a-a3b3b3adfe9b",
    "wiki": "Philip Glass"
  },
  "psy": {
    "area": "Japan",
    "gender": "female",
    "mbid": "20c73d92-93c4-4494-a8cf-52e8ab13021b"
  },
  "quincy-jones": {
    "area": "United States",
    "gender": "male",
    "mbid": "5803c81e-739a-4057-9a5c-cf84e55db630",
    "wiki": "Quincy Jones"
  },
  "redone": {
    "area": "Sweden",
    "gender": "male",
    "mbid": "8c84402d-f282-4afc-8d64-049bdaabb92d",
    "wiki": "RedOne"
  },
  "rita-coolidge": {
    "wiki": "Rita Coolidge"
  },
  "rita-ora": {
    "wiki": "Rita Ora"
  },
  "robert-plant": {
    "wiki": "Robert Plant"
  },
  "rosalia-2": {
    "wiki": "Rosalía"
  },
  "ruben-blades": {
    "area": "Panama",
    "gender": "male",
    "mbid": "f050673a-dfb3-4200-b057-bf78213de36c",
    "wiki": "Rubén Blades"
  },
  "sabrina-carpenter": {
    "area": "United States",
    "gender": "female",
    "mbid": "1882fe91-cdd9-49c9-9956-8e06a3810bd4",
    "wiki": "Sabrina Carpenter"
  },
  "salif-keita": {
    "area": "Mali",
    "gender": "male",
    "mbid": "b29a24ff-2c55-437e-867b-1456c9f3f73e",
    "wiki": "Salif Keita"
  },
  "sam-cooke": {
    "wiki": "Sam Cooke"
  },
  "sara-bareilles": {
    "wiki": "Sara Bareilles"
  },
  "sarah-vaughan": {
    "area": "United States",
    "gender": "female",
    "mbid": "351d8bdf-33a1-45e2-8c04-c85fad20da55",
    "wiki": "Sarah Vaughan"
  },
  "sebastian-bach": {
    "wiki": "Sebastian Bach"
  },
  "selena-gomez": {
    "area": "United States",
    "gender": "female",
    "mbid": "e4bc69e2-a064-4f93-ada1-f7f209cc1cc3",
    "wiki": "Selena Gomez"
  },
  "serj-tankian": {
    "wiki": "Serj Tankian"
  },
  "shakira-2": {
    "wiki": "Shakira"
  },
  "shawn-mendes": {
    "area": "Canada",
    "gender": "male",
    "mbid": "b7d92248-97e3-4450-8057-6fe06738f735",
    "wiki": "Shawn Mendes"
  },
  "sheryl-crow": {
    "wiki": "Sheryl Crow"
  },
  "shyne": {
    "area": "United States",
    "gender": "male",
    "mbid": "b85791db-53bf-4847-ae63-75f279afd36e",
    "wiki": "Shyne"
  },
  "sinead-o-connor": {
    "wiki": "Sinéad O'Connor"
  },
  "sri-chinmoy": {
    "wiki": "Sri Chinmoy"
  },
  "stevie-nicks": {
    "wiki": "Stevie Nicks"
  },
  "tammi-terrell": {
    "wiki": "Tammi Terrell"
  },
  "tate-mcrae": {
    "area": "Canada",
    "gender": "female",
    "mbid": "f9133869-f87c-459c-9aa7-2f176cda7e06",
    "wiki": "Tate McRae"
  },
  "taylor-swift": {
    "area": "United States",
    "gender": "female",
    "mbid": "20244d07-534f-4eff-b4d4-930878889970",
    "wiki": "Taylor Swift"
  },
  "thelonious-monk": {
    "wiki": "Thelonious Monk"
  },
  "tim-mcgraw": {
    "area": "United States",
    "gender": "male",
    "mbid": "7e5cfc9a-e9e1-46f1-b81a-861b12049488",
    "wiki": "Tim McGraw"
  },
  "toni-braxton": {
    "wiki": "Toni Braxton"
  },
  "vanessa-paradis": {
    "wiki": "Vanessa Paradis"
  },
  "victor-jara": {
    "area": "Chile",
    "gender": "male",
    "mbid": "b7e6a7fb-1d38-4ad8-bd97-c125ad4421ab"
  },
  "violeta-parra": {
    "wiki": "Violeta Parra"
  },
  "wendy-carlos": {
    "area": "United States",
    "gender": "female",
    "mbid": "7e3b3173-2c1f-42c0-8544-0e6d19bb181f",
    "wiki": "Wendy Carlos"
  },
  "whitney-houston": {
    "wiki": "Whitney Houston"
  },
  "willie-nelson": {
    "area": "United States",
    "gender": "male",
    "mbid": "668fd73c-bf54-4310-a139-305517f05311",
    "wiki": "Willie Nelson"
  },
  "yo-yo-ma": {
    "wiki": "Yo-Yo Ma"
  },
  "zayn-malik": {
    "wiki": "Zayn Malik"
  },
  "zendaya": {
    "wiki": "Zendaya"
  }
};

// ---------------------------------------------------------------------------
// WIKI_DISAMBIG — artist name → the Wikipedia title that actually resolves.
//
// The entries where a naive guess fails, filtered to people: "(musician)",
// "(singer)", "(record producer)" and the like. Band disambiguations were
// dropped, since a band is not a person and this roster only holds people.
//
// This is the fix for a failure that has already cost this roster real entries —
// Yves Saint Laurent resolves to a disambiguation page, and was skipped twice
// before anyone thought to look up the qualified title.
// ---------------------------------------------------------------------------
export const WIKI_DISAMBIG = {
  "1.8.7": "Jordana (producer)",
  "12th Planet": "12th Planet (musician)",
  "ALEX PRESTON": "Alex Preston (singer)",
  "ASCA": "Asca (singer)",
  "ATA": "Ata (DJ)",
  "AZ": "AZ (rapper)",
  "Abdominal": "Abdominal (rapper)",
  "Abigail": "Abigail (singer)",
  "Actress": "Actress (musician)",
  "Adam Bomb": "Adam Bomb (musician)",
  "Adam Brand": "Adam Brand (musician)",
  "Adam Green": "Adam Green (musician)",
  "Adam Gregory": "Adam Gregory (singer)",
  "Adam Lane Trio": "Adam Lane (musician)",
  "Adam Watts": "Adam Watts (musician)",
  "Adaro": "Adaro (DJ)",
  "Adeem": "Adeem (rapper)",
  "Ado": "Ado (singer)",
  "Aeroplane": "Aeroplane (musician)",
  "Afgan": "Afgan (singer)",
  "Aga": "AGA (singer)",
  "Agent X": "Agent X (producers)",
  "Agoria": "Agoria (musician)",
  "Aim": "Aim (musician)",
  "Aitch": "Aitch (rapper)",
  "Akifumi Nakajima": "Aube (musician)",
  "Al Johnson": "Al Johnson (musician)",
  "Al Jones": "Al Jones (drummer)",
  "Al Wilson": "Al Wilson (singer)",
  "Alain Caron": "Alain Caron (bassist)",
  "Alan Lamb": "Alan Lamb (musician)",
  "Alastair McDonald": "Alastair McDonald (musician)",
  "Albert Frey": "Albert Frey (musician)",
  "Alberto Castillo": "Alberto Castillo (performer)",
  "Alberto Domínguez": "Alberto Domínguez (composer)",
  "Albino": "Albino (Rapper)",
  "Alda": "Alda (singer)",
  "Alex Calder": "Alex Calder (musician)",
  "Alex Cameron": "Alex Cameron (musician)",
  "Alex Fergusson": "Alex Fergusson (musician)",
  "Alex Wilson": "Alex Wilson (musician)",
  "Alexander Kowalski": "Alexander Kowalski (musician)",
  "Alfredo Rodriguez": "Alfredo Rodríguez (pianist, born 1985)",
  "Alice Clark": "Alice Clark (singer)",
  "Alice Russell": "Alice Russell (singer)",
  "Alien Project": "Alien Project (musician)",
  "Alika & Nueva Alianza": "Alika (singer)",
  "Alisha": "Alisha (singer)",
  "Alkaline": "Alkaline (musician)",
  "Allan Gray": "Allan Gray (composer)",
  "Allan Taylor": "Allan Taylor (musician)",
  "Allison Miller": "Allison Miller (drummer)",
  "Alonzo": "Alonzo (rapper)",
  "Alvaro Díaz": "Álvaro Díaz (rapper)",
  "Amber": "Amber (singer)",
  "Amtrac": "Amtrac (musician)",
  "Anaís": "Anaís (singer)",
  "Andrea Martin": "Andrea Martin (musician)",
  "Andrea Parker": "Andrea Parker (musician)",
  "Andrew Hill": "Andrew Hill (pianist)",
  "Andrew Huang": "Andrew Huang (musician)",
  "Andrew Lewis": "Andrew Lewis (composer)",
  "Andrzej Zaucha": "Andrzej Zaucha (singer)",
  "Andrés Jiménez": "Andrés Jiménez (singer)",
  "Andy Bell": "Andy Bell (singer)",
  "Andy Kim": "Andy Kim (singer)",
  "Andy Kirk": "Andy Kirk (musician)",
  "Andy Lewis": "Andy Lewis (producer)",
  "Andy Moor": "Andy Moor (guitarist)",
  "Andy Park": "Andy Park (musician)",
  "Andy Russell": "Andy Russell (singer)",
  "Angel Blue and the Prophets Band": "Angel Blue (singer)",
  "Angela Autumn": "Angela Autumn (musician)",
  "Angelica Sanchez": "Angelica Sanchez (musician)",
  "Angelina": "Angelina (American singer)",
  "Angèle": "Angèle (singer)",
  "Anitta": "Anitta (singer)",
  "Ann Richards": "Ann Richards (singer)",
  "Anna Webber": "Anna Webber (musician)",
  "Anne Savage": "Anne Savage (DJ)",
  "Anne Wilson": "Anne Wilson (musician)",
  "Annie": "Annie (singer)",
  "Annie Hart": "Annie Hart (musician)",
  "Annie Laurie": "Annie Laurie (musician)",
  "Ano": "Ano (singer)",
  "Anouk": "Anouk (singer)",
  "Anthony Collins": "Anthony Collins (composer)",
  "Anthony Davis": "Anthony Davis (composer)",
  "Anthony Evans": "Anthony Evans (singer)",
  "Anthony Green": "Anthony Green (musician)",
  "Anthony Jackson": "Anthony Jackson (musician)",
  "Anthony Johnson": "Anthony Johnson (musician)",
  "Anthony Ortega": "Anthony Ortega (musician)",
  "Antonio Vega": "Antonio Vega (singer)",
  "Aoife Wolf": "Ursula+Burns+(musician)",
  "Apache": "Apache (rapper)",
  "Apache Indian": "Apache Indian (musician)",
  "Apex": "Apex (musician)",
  "Aphrodite": "Aphrodite (musician)",
  "Apparat": "Apparat (musician)",
  "Aqualung": "Aqualung (musician)",
  "Aramide": "Aramide (musician)",
  "Arash": "Arash (singer)",
  "Arca": "Arca (musician)",
  "Archigram": "Archigram (artiste français)",
  "Ari & Mia": "Drake+(musician)",
  "Armando": "Armando (producer)",
  "Artemas": "Artemas (musician)",
  "Arthur Adams": "Arthur Adams (singer)",
  "Arthur Brown": "Arthur Brown (musician)",
  "Arthur Jones": "Arthur Jones (saxophonist)",
  "Arthur Lee": "Arthur Lee (musician)",
  "Arthur Miles": "Arthur Miles (musician, born 1949)",
  "Arthur Russell": "Arthur Russell (musician)",
  "Artificial Eye": "Artificial Eye (musician)",
  "Asaka": "Asaka (musician)",
  "Ashanti": "Ashanti (singer)",
  "Asher D": "Asher D (rapper)",
  "Atlanta": "Atlanta (singer)",
  "Atumpan": "Atumpan (singer)",
  "Aube": "Aube (musician)",
  "Austin Roberts": "Austin Roberts (singer)",
  "Autumn!": "Autumn (rapper)",
  "Avishai Cohen": "Avishai Cohen (bassist)",
  "Azana": "Azana (singer)",
  "B.I": "B.I (rapper)",
  "B6": "B6 (musician)",
  "BRANDON": "Brandon (artisti)",
  "BT": "BT (musician)",
  "Baasch": "Baasch (musician)",
  "Baby Face Leroy": "Leroy Foster (musician)",
  "Baby Huey": "Baby Huey (singer)",
  "Babyface": "Babyface (musician)",
  "Bachelorette": "Bachelorette (singer)",
  "Bad Azz": "Bad Azz (rapper)",
  "Baden Powell": "Baden Powell (guitarist)",
  "Bahar": "Bahar (Rapperin)",
  "Bajka": "Bajka (musician)",
  "Bana": "Bana (singer)",
  "Barbara Jones": "Barbara Jones (singer)",
  "Barlow": "Barlow (musician)",
  "Barry Andrews": "Barry Andrews (musician)",
  "Barry Brown": "Barry Brown (singer)",
  "Barry Lynn": "Boxcutter (musician)",
  "Barry Miles": "Barry Miles (musician)",
  "Basenji": "Basenji (producer)",
  "Basil Gabbidon": "Sanchez (singer)",
  "Baths": "Baths (musician)",
  "Bayonne": "Bayonne (musician)",
  "Bellah": "Bellah (singer)",
  "Ben Frost": "Ben Frost (musician)",
  "Ben Johnston": "Ben Johnston (composer)",
  "Ben Shaw": "Ben Shaw (DJ)",
  "Ben Weber": "Ben Weber (composer)",
  "Ben Williams": "Ben Williams (musician)",
  "Beneficence": "Beneficence (rapper)",
  "Benga": "Benga (musician)",
  "Benga & Coki": "Benga (musician)",
  "Benge": "Benge (musician)",
  "Beni": "Beni (singer)",
  "Benjamin": "Benjamin (singer)",
  "Benny GORDON & the Soul Brothers": "Benny Gordon (singer)",
  "Ber": "Ber (musician)",
  "Berner": "Berner (rapper)",
  "Bessie Jones": "Bessie Jones (American singer)",
  "Betty Bennett": "Betty Bennett (singer)",
  "Beyries": "Beyries (singer)",
  "Bia": "Bia (rapper)",
  "Big Black": "Big Black (musician)",
  "Bilal": "Bilal (American singer)",
  "Bill Anderson": "Bill Anderson (singer)",
  "Bill Baird": "Bill Baird (musician)",
  "Bill Barron": "Bill Barron (musician)",
  "Bill Boyd": "Bill Boyd (musician)",
  "Bill Callahan": "Bill Callahan (musician)",
  "Bill Cole": "Bill Cole (musician)",
  "Bill Douglas": "Bill Douglas (musician)",
  "Bill Emerson": "Bill Emerson (musician)",
  "Bill Holman": "Bill Holman (musician)",
  "Bill Hopkins": "Bill Hopkins (composer)",
  "Bill Jennings": "Bill Jennings (guitarist)",
  "Bill Keith": "Bill Keith (musician)",
  "Bill Nelson": "Bill Nelson (musician)",
  "Bill Perkins": "Bill Perkins (saxophonist)",
  "Bill Stewart": "Bill Stewart (musician)",
  "Bill Summers": "Bill Summers (musician)",
  "Billy Bland": "Billy Bland (singer)",
  "Billy Butler": "Billy Butler (singer)",
  "Billy Van": "Billy Van (musician)",
  "Billy Wright": "Billy Wright (musician)",
  "Biosphere": "Biosphere (musician)",
  "Black": "Black (singer)",
  "Blackdown": "Blackdown (musician)",
  "Blackmill": "Blackmill (musician)",
  "Blanche": "Blanche (singer)",
  "Blanke": "Blanke (DJ)",
  "Blinky": "Blinky (singer)",
  "Blinky Bill": "Blinky Bill (musician)",
  "Blowfly": "Blowfly (artist)",
  "Blu Peter": "Peter Harris (producer)",
  "Bob Cooper": "Bob Cooper (musician)",
  "Bob Davenport": "Bob Davenport (singer)",
  "Bob Gordon": "Bob Gordon (saxophonist)",
  "Bob James": "Bob James (musician)",
  "Bob Morrison": "Bob Morrison (songwriter)",
  "Bob Moses": "Bob Moses (musician)",
  "Bob Reynolds": "Bob Reynolds (saxophonist)",
  "Bob Stewart": "Bob Stewart (musician)",
  "Bob Welch": "Bob Welch (musician)",
  "Bobby Bryant": "Bobby Bryant (musician)",
  "Bobby Patterson": "Bobby Patterson (musician)",
  "Bobby Powell": "Bobby Powell (musician)",
  "Bobby Rush": "Bobby Rush (musician)",
  "Bobby Scott": "Bobby Scott (musician)",
  "Bonobo": "Bonobo (musician)",
  "Boris Blank": "Boris Blank (musician)",
  "Bow Wow": "Bow Wow (rapper)",
  "Boxcutter": "Boxcutter (musician)",
  "BoyWithUke": "Chandol (singer)",
  "Brandon": "Brandon (artisti)",
  "Brandon Lake": "Brandon Lake (musician)",
  "Brian Houston": "Brian Houston (musician)",
  "Brian Hughes": "Brian Hughes (musician)",
  "Brian Lynch": "Brian Lynch (musician)",
  "Brooks": "Brooks (DJ)",
  "Buccaneer": "Buccaneer (musician)",
  "Buddy Clark": "Buddy Clark (singer)",
  "Bunker Hill": "Bunker Hill (musician)",
  "Burial": "Burial (musician)",
  "Burial & Kode9": "Burial (musician)",
  "Burns": "Burns (musician)",
  "Buscemi": "Buscemi (DJ)",
  "Buster Brown": "Buster Brown (musician)",
  "Bülow": "Bülow (singer)",
  "CALI": "Cali (singer)",
  "CDQ": "CDQ (rapper)",
  "CFCF": "CFCF (musician)",
  "COH": "CoH (musician)",
  "Calibre": "Calibre (musician)",
  "Calvin Johnson": "Calvin Johnson (musician)",
  "Calvin Russell": "Calvin Russell (musician)",
  "Camellia": "Camellia (musician)",
  "Camisra": "Tall Paul (DJ)",
  "Candyman": "Candyman (rapper)",
  "Caribou": "Caribou (musician)",
  "Carl Anderson": "Carl Anderson (singer)",
  "Carl Davis": "Carl Davis (record producer)",
  "Carl Hall": "Carl Hall (singer)",
  "Carl Martin": "Carl Martin (musician)",
  "Carl Smith": "Carl Smith (musician)",
  "Carl Thomas": "Carl Thomas (singer)",
  "Carlos García": "Carlos García (musician)",
  "Carlos Henriquez": "Carlos Henriquez (musician)",
  "Carman": "Carman (singer)",
  "Carol Williams": "Carol Williams (singer)",
  "Caroline Henderson": "Caroline Henderson (singer)",
  "Carrara": "Carrara (singer)",
  "Cassiano": "Cassiano (singer)",
  "Casual": "Casual (rapper)",
  "Catcall": "Catcall (musician)",
  "Catherine Russell": "Catherine Russell (singer)",
  "Cavs": "Michael Cavanagh (drummer)",
  "Cesare Cremonini": "Cesare Cremonini (singer)",
  "Cex": "Cex (musician)",
  "Chad Valley": "Chad Valley (musician)",
  "Cham": "Cham (singer)",
  "Chanelle": "Chanelle (singer)",
  "Chara": "Chara (singer)",
  "Charlene": "Charlene (singer)",
  "Charles Avery": "Charles Avery (pianist)",
  "Charles Bradley": "Charles Bradley (singer)",
  "Charles Brown": "Charles Brown (musician)",
  "Charles Dodge": "Charles Dodge (composer)",
  "Charles Greenlee": "Charles Greenlee (musician)",
  "Charles Hayward": "Charles Hayward (drummer)",
  "Charles McPherson": "Charles McPherson (musician)",
  "Charles Sullivan": "Charles Sullivan (musician)",
  "Charles Tyler": "Charles Tyler (musician)",
  "Charles Webster": "Charles Webster (musician)",
  "Charles Wright": "Charles Wright (musician)",
  "Charlie Chaplin": "Charlie Chaplin (singer)",
  "Charlie Cunningham": "Charlie Cunningham (musician)",
  "Charlie Hall": "Charlie Hall (musician)",
  "Charlie May": "Charlie May (producer)",
  "Charlie Wilson": "Charlie Wilson (musician)",
  "Charmaine": "Charmaine (musician)",
  "Cheat Codes": "Cheat Codes (DJs)",
  "Chela": "Chela (singer)",
  "Cheryl Cole": "Cheryl (singer)",
  "Chicane": "Chicane (musician)",
  "Chima": "Chima (singer)",
  "Chipmunk": "Chip (rapper)",
  "Chocolat": "Chocolat (singer)",
  "Chop Shop": "Chop Shop (musician)",
  "Chords": "Chords (musician)",
  "Chris Bell": "Chris Bell (musician)",
  "Chris Clark": "Clark (musician)",
  "Chris Cohen": "Chris Cohen (musician)",
  "Chris Duarte": "Chris Duarte (musician)",
  "Chris Rodriguez": "Chris Rodriguez (singer)",
  "Chris Thomas": "Chris Thomas (record producer)",
  "Chris Watson": "Chris Watson (musician)",
  "Christ.": "Christ. (musician)",
  "Christian Smith": "Christian Smith (DJ)",
  "Christian Wolff": "Christian Wolff (composer)",
  "Christopher": "Prince (musician)",
  "Christopher Williams": "Christopher Williams (singer)",
  "Cindy Morgan": "Cindy Morgan (singer)",
  "Claire Cronin": "Claire Cronin (singer-songwriter)",
  "Claire Martin": "Claire Martin (singer)",
  "Clams Casino": "Clams Casino (musician)",
  "Clarence Reid": "Blowfly (musician)",
  "Clementine": "Clementine (musician)",
  "Clifford Scott": "Clifford Scott (musician)",
  "Clint Eastwood": "Clint Eastwood (musician)",
  "Clive Palmer": "Clive Palmer (musician)",
  "Clothilde": "Clothilde (musician)",
  "Clubroot": "Clubroot (musician)",
  "Clémentine": "Clémentine (musician)",
  "Coati Mundi": "Coati Mundi (musician)",
  "Cochise": "Cochise (rapper)",
  "Code Black": "Code Black (DJ)",
  "Colleen": "Colleen (musician)",
  "Common": "Common (rapper)",
  "Corbin": "Corbin (musician)",
  "Corey Hart": "Corey Hart (singer)",
  "Craig Armstrong": "Craig Armstrong (composer)",
  "Craig Campbell": "Craig Campbell (singer)",
  "Craig Richards": "Craig Richards (DJ)",
  "Crime Boss": "Crime Boss (rapper)",
  "Cristina": "Cristina (singer)",
  "Cro": "Cro (Rapper)",
  "Crowder": "Crowder (musician)",
  "Cuco": "Cuco (musician)",
  "Curtis Jones": "Curtis Jones (pianist)",
  "DAVID PENN": "David Penn (DJ)",
  "DAX": "Dax (rapper)",
  "DJ Hazard": "DJ Hazard (musician)",
  "DMX": "DMX (rapper)",
  "Daedelus": "Daedelus (musician)",
  "Dale Watson": "Dale Watson (singer)",
  "Damian": "Damian (musician)",
  "Dan Costa": "Dan Costa (musician)",
  "Dan Friel": "Dan Friel (musician)",
  "Dan Hicks": "Dan Hicks (singer)",
  "Dan Reeder": "Dan Reeder (musician)",
  "Dan Wilson": "Dan Wilson (musician)",
  "Danger Mouse": "Danger Mouse (musician)",
  "Daniel Avery": "Daniel Avery (musician)",
  "Daniel Bell": "Daniel Bell (musician)",
  "Daniel Boone": "Daniel Boone (singer)",
  "Daniel Carter": "Daniel Carter (musician)",
  "Daniel Davies": "Daniel Davies (musician)",
  "Daniel Goode": "Daniel Goode (composer)",
  "Daniel Jones": "Daniel Jones (musician)",
  "Daniel Paul O'Sullivan": "Daniel O'Sullivan (musician)",
  "Daniel Santos": "Daniel Santos (singer)",
  "Danny Ray": "Danny Ray (singer)",
  "Danny Williams": "Danny Williams (singer)",
  "Danny Wright": "Danny Wright (pianist)",
  "Darina": "Darina (singer)",
  "Darkus": "Mark Rutherford (composer)",
  "Darrell Brown": "Darrell Brown (musician)",
  "Darrell Evans": "Darrell Evans (musician)",
  "Dasha": "Dasha (singer)",
  "Datsik": "Datsik (musician)",
  "Dave Alexander": "Dave Alexander (musician)",
  "Dave Armstrong": "Dave Armstrong (DJ)",
  "Dave Clarke": "Dave Clarke (DJ)",
  "Dave Kelly": "Dave Kelly (musician)",
  "Dave Lee": "Dave Lee (DJ)",
  "Dave Phillips": "Dave Phillips (musician)",
  "Dave Stewart": "Dave Stewart (musician, born 1950)",
  "David August": "David August (musician)",
  "David Axelrod": "David Axelrod (musician)",
  "David Barrett": "David Barrett (musician)",
  "David Darling": "David Darling (musician)",
  "David Denny": "David Denny (musician)",
  "David Dunne": "David Dunne (DJ)",
  "David Holmes": "David Holmes (musician)",
  "David Houston": "David Houston (singer)",
  "David Kilgour": "David Kilgour (musician)",
  "David King": "David King (drummer)",
  "David Lang": "David Lang (composer)",
  "David Leonard": "David Leonard (singer)",
  "David Levy": "David Levy (Bassist)",
  "David Lowery": "David Lowery (musician)",
  "David Ludwig": "David Ludwig (composer)",
  "David McWilliams": "David McWilliams (musician)",
  "David Mead": "David Mead (musician)",
  "David Murray": "David Murray (saxophonist)",
  "David Parsons": "David Parsons (composer)",
  "David Phelps": "David Phelps (musician)",
  "David Porter": "David Porter (musician)",
  "David Quinlan": "David Quinlan (singer)",
  "David Rose": "David Rose (songwriter)",
  "David Sánchez": "David Sánchez (musician)",
  "David Werner": "David Werner (musician)",
  "David Young": "David Young (guitarist)",
  "Davy Jones": "Davy Jones (musician)",
  "DeVita": "DeVita (singer)",
  "Deadbeat": "Deadbeat (musician)",
  "Deakin": "Deakin (musician)",
  "Dean Brown": "Dean Brown (guitarist)",
  "Dee Edwards": "Dee Edwards (singer)",
  "Deep Blue": "Deep Blue (musician)",
  "Delroy Edwards": "Delroy Edwards (musician)",
  "Demarco": "Demarco (musician)",
  "Demon": "Demon (musician)",
  "Deon Jackson": "Deon Jackson (singer)",
  "Derek Bailey": "Derek Bailey (guitarist)",
  "Derrick May": "Derrick May (musician)",
  "Devlin": "Devlin (rapper)",
  "Diana Hamilton": "Diana Hamilton (musician)",
  "Dido": "Dido (singer)",
  "Diesel": "Diesel (musician)",
  "Dillinger": "Dillinger (musician)",
  "Dillon": "Dillon (singer)",
  "Dinka": "Dinka (DJ)",
  "Dio": "Dio (rapper)",
  "Displacer": "Displacer (musician)",
  "Distance": "Distance (musician)",
  "Diverse": "Diverse (rapper)",
  "Dixon": "Dixon (DJ)",
  "Dobie": "Dobie (musician)",
  "Doda": "Doda (singer)",
  "Domino": "Domino (rapper)",
  "Don Bryant": "Don Bryant (songwriter)",
  "Don Carlos": "Don Carlos (singer)",
  "Don Cherry": "Don Cherry (singer)",
  "Don Dixon": "Don Dixon (musician)",
  "Don Francisco": "Don Francisco (musician)",
  "Don Gillis": "Don Gillis (composer)",
  "Don Julian": "Don Julian (musician)",
  "Don Li": "Don Li (composer/musician)",
  "Don Mckenzie": "Don McKenzie (musician)",
  "Don Potter": "Don Potter (musician)",
  "Don Robertson": "Don Robertson (composer)",
  "Donna Hughes": "Donna Hughes (musician)",
  "Doof": "Doof (musician)",
  "Dosh": "Dosh (musician)",
  "Doss": "Doss (musician)",
  "Dotan": "Dotan (singer)",
  "Douglas Miller": "Douglas Miller (musician)",
  "Drake": "Drake (rapper)",
  "Dram": "DRAM (musician)",
  "Dred Scott": "Dred Scott (rapper)",
  "Dudley Perkins": "Dudley Perkins (rapper)",
  "Dudley Sibley & Peter Austin": "Etana (musician)",
  "Duffy": "Duffy (singer)",
  "Duki": "Duki (rapper)",
  "E-Smoove": "Eric Miller (musician)",
  "EDX": "EDX (DJ)",
  "Earl Thomas": "Earl Thomas (musician)",
  "Eartheater": "Eartheater (musician)",
  "Ed Bell": "Ed Bell (musician)",
  "Ed Case": "Ed Case (musician)",
  "Ed Wilson": "Ed Wilson (singer)",
  "Eddie Henderson": "Eddie Henderson (musician)",
  "Edis": "Edis (singer)",
  "Edith Wilson": "Edith Wilson (singer)",
  "Edward Ball": "Ed Ball (musician)",
  "Edward Johnson": "Edward Johnson (composer)",
  "Edward Simon": "Edward Simon (musician)",
  "Edwin": "Edwin (musician)",
  "Ekali": "Ekali (musician)",
  "El Cabrero": "El Cabrero (singer)",
  "Eliel": "Eliel (producer)",
  "Elizabeth Mitchell": "Elizabeth Mitchell (musician)",
  "Elizabeth Shepherd": "Elizabeth Shepherd (musician)",
  "Elodie": "Elodie (singer)",
  "Eluvium": "Eluvium (musician)",
  "Emancipator": "Emancipator (musician)",
  "Emma Stevens": "Emma Stevens (singer)",
  "Emmanuel": "Emmanuel (singer)",
  "Emmanuel Milwaukee": "Emmanuel (singer)",
  "Engelbert Humperdinck": "Engelbert Humperdinck (singer)",
  "Enji": "Enji (singer)",
  "Eon": "Eon (musician)",
  "Epo": "Epo (singer)",
  "Eric Taylor": "Eric Taylor (musician)",
  "Eric Watson": "Eric Watson (musician)",
  "Ernest Wilson": "Ernest Wilson (singer)",
  "Ernie Smith": "Ernie Smith (singer)",
  "Eskiboy": "Wiley (musician)",
  "Esteban": "Esteban (musician)",
  "Estelle": "Estelle (musician)",
  "Esther Rose": "Esther Rose (musician)",
  "Ethan James": "Ethan James (producer)",
  "Evelyn Knight": "Evelyn Knight (singer)",
  "Evie": "Evie (singer)",
  "Example": "Example (musician)",
  "Excision": "Excision (musician)",
  "Exuma": "Exuma (musician)",
  "FISHER": "Fisher (musician)",
  "Fabio": "Fabio (DJ)",
  "Family Love": "Michael Palmer (musician)",
  "Faultline": "Faultline (musician)",
  "Fave": "Fave (singer)",
  "Favorite": "Favorite (Rapper)",
  "Feder": "Feder (DJ)",
  "Feed Me": "Feed Me (musician)",
  "Feist": "Feist (singer)",
  "Felipe Rodriguez": "Felipe Rodríguez (singer)",
  "Felix": "Felix (musician)",
  "Ferdinand David": "Ferdinand David (musician)",
  "Fergie": "Fergie (DJ)",
  "Fernando Velázquez": "Fernando Velázquez (composer)",
  "Fey": "Fey (singer)",
  "Figure": "Figure (musician)",
  "Fink": "Fink (singer)",
  "Fish": "Fish (singer)",
  "Fish Plants": "Fish (singer)",
  "Flame": "Flame (rapper)",
  "Flea": "Flea (musician)",
  "Fletcher": "Fletcher (singer)",
  "Floby": "Floby (musician)",
  "Flood": "Flood (producer)",
  "Florence K": "Florence K (singer)",
  "Flume": "Flume (musician)",
  "Fola": "Fola (singer)",
  "Foley": "Foley (musician)",
  "Footsie": "Footsie (musician)",
  "Forrest": "Forrest (singer)",
  "Foxes": "Foxes (singer)",
  "Frances White": "Frances White (composer)",
  "Francisco Escudero": "Francisco Escudero (composer)",
  "Francisco Guerrero": "Francisco Guerrero (composer)",
  "Franco Evangelisti": "Franco Evangelisti (composer)",
  "Frank Hewitt": "Frank Hewitt (musician)",
  "Frank Hunter": "Frank Hunter (musician)",
  "Frank Jenkins": "Frank Jenkins (musician)",
  "Frank Morgan": "Frank Morgan (musician)",
  "Frank Stokes": "Frank Stokes (musician)",
  "Frank Wilson": "Frank Wilson (musician)",
  "Fratelli Di Soledad": "Claye (musician)",
  "Fred Anderson": "Fred Anderson (musician)",
  "Fred Jackson": "Fred Jackson (saxophonist)",
  "Fred V": "Fred V (record producer)",
  "Freddie James": "Freddie James (musician)",
  "Frederick Knight": "Frederick Knight (singer)",
  "Frederik": "Frederik (singer)",
  "Freemasons": "Freemasons (DJs)",
  "Frisco": "Frisco (rapper)",
  "Frivolous": "Daniel Gardner (musician)",
  "Fuego": "Fuego (singer)",
  "Function": "Function (musician)",
  "Gabriel Jackson": "Gabriel Jackson (composer)",
  "Gabrielle": "Gabrielle (singer)",
  "Gaika": "Gaika (musician)",
  "Gala": "Gala (singer)",
  "Garou": "Garou (singer)",
  "Gary Chapman": "Gary Chapman (musician)",
  "Gary Smith": "Gary Smith (record producer)",
  "Gary Stewart": "Gary Stewart (singer)",
  "Gary Wilson": "Gary Wilson (musician)",
  "Gas": "Gas (musician)",
  "Gaudi": "Gaudi (musician)",
  "Gazebo": "Gazebo (musician)",
  "General Midi": "General Midi (DJ)",
  "Gentleman": "Gentleman (musician)",
  "George Adams": "George Adams (musician)",
  "George Barnett": "George Barnett (musician, born 1988)",
  "George Benjamin": "George Benjamin (composer)",
  "George Ducas": "George Ducas (singer)",
  "George Fitzgerald": "George FitzGerald (musician)",
  "George Freeman": "George Freeman (guitarist)",
  "George Lloyd": "George Lloyd (composer)",
  "George Lynch": "George Lynch (musician)",
  "George Onslow": "George Onslow (composer)",
  "George Russell": "George Russell (composer)",
  "George Soule": "George Soulé (musician)",
  "George Templeton Strong": "George Templeton Strong (composer)",
  "George Walker": "George Walker (composer)",
  "Geotic": "Baths (musician)",
  "Gerardo": "Gerardo (musician)",
  "Gerry Gibbs": "Gerry Gibbs (musician)",
  "Getter": "Getter (DJ)",
  "Ghali": "Ghali (rapper)",
  "Giggs": "Giggs (rapper)",
  "Gilla": "Gilla (singer)",
  "Gillette": "Gillette (singer)",
  "Giovanni Battista Fontana": "Giovanni Battista Fontana (composer)",
  "Giovanni Marradi": "Giovanni Marradi (musician)",
  "Giro": "Giro (musician)",
  "Glen Phillips": "Glen Phillips (singer)",
  "Glenn Hughes": "Glenn Hughes (musician)",
  "Glenn Morrison": "Glenn Morrison (DJ)",
  "Gloria Scott": "Gloria Scott (singer)",
  "Govi": "Govi (musician)",
  "Graham Walsh": "Graham Walsh (musician)",
  "Grant Nelson": "Grant Nelson (DJ)",
  "Green Velvet": "Green Velvet (musician)",
  "Greg Adams": "Greg Adams (musician)",
  "Greg Ellis": "Greg Ellis (musician)",
  "Greg Wilson": "Greg Wilson (DJ)",
  "Grido": "Grido (rapper)",
  "Griff": "Griff (singer)",
  "Grouper": "Grouper (musician)",
  "Gru": "Gru (rapper)",
  "Gummy": "Gummy (singer)",
  "Gunna": "Gunna (rapper)",
  "Guns Of Brixton": "Mavado (singer)",
  "Guru": "Guru (rapper)",
  "Gusto": "Gusto (producer)",
  "Guy Mitchell": "Guy Mitchell (singer)",
  "Göksel": "Göksel (singer)",
  "Gökçe": "Gökçe (singer)",
  "Hainbach": "Hainbach (musician)",
  "Halsey": "Halsey (singer)",
  "Hank Thompson": "Hank Thompson (musician)",
  "Hannah Cohen": "Hannah Cohen (singer)",
  "Hardstone": "Hardstone (musician)",
  "Haroon": "Haroon (singer)",
  "Harrison, Bobby": "Bobby Harrison (musician)",
  "Harry Arnold": "Harry Arnold (musician)",
  "Haruka Nakamura": "Haruka Nakamura (composer)",
  "Hatchie": "Hatchie (musician)",
  "Hayden": "Hayden (musician)",
  "Headliner": "Headliner (DJ)",
  "Hedegaard": "Hedegaard (DJ)",
  "Helen Ward": "Helen Ward (singer)",
  "Helen Watson": "Helen Watson (singer-songwriter)",
  "Hellberg": "Hellberg (DJ)",
  "Henri Duparc": "Henri Duparc (composer)",
  "Henry Gray": "Henry Gray (musician)",
  "Henry Kaiser": "Henry Kaiser (musician)",
  "Henry Paul Band": "Henry Paul (musician)",
  "Henry Townsend": "Henry Townsend (musician)",
  "Herve": "Hervé (composer)",
  "Hervé": "Hervé (composer)",
  "Hint": "Hint (musician)",
  "Holly Golightly": "Holly Golightly (singer)",
  "Horace Brown": "Horace Brown (musician)",
  "Horse": "Horse (musician)",
  "Hot Rod @hotrodthegod": "Hot Rod (rapper)",
  "Hot Sugar": "Hot Sugar (musician)",
  "Howard Riley": "Howard Riley (musician)",
  "Hozier": "Hozier (musician)",
  "Hugh Blair": "Hugh Blair (composer)",
  "Hugh Davies": "Hugh Davies (composer)",
  "Héctor Acosta \"El Torito\"": "Héctor Acosta (singer)",
  "IDK": "IDK (rapper)",
  "Ian Hunter": "Ian Hunter (singer)",
  "Ian Lloyd": "Ian Lloyd (musician)",
  "Ian Matthews": "Ian Matthews (drummer)",
  "Ian McCulloch": "Ian McCulloch (singer)",
  "Ian Wallace": "Ian Wallace (drummer)",
  "Iasos": "Iasos (musician)",
  "Ida Aurora": "Aurora (singer)",
  "Ils": "Ils (musician)",
  "Ima": "Ima (singer)",
  "Inez": "Inez (singer)",
  "Inji": "Inji (singer)",
  "Irving Kaufman": "Irving Kaufman (singer)",
  "J.J. Jackson": "J. J. Jackson (singer)",
  "JOO": "Joo (singer)",
  "Jack Daugherty": "Jack Daugherty (musician)",
  "Jack Johnson": "Jack Johnson (musician)",
  "Jack Jones": "Jack Jones (American singer)",
  "Jack McManus": "Jack McManus (singer)",
  "Jack Owens": "Jack Owens (singer-songwriter)",
  "Jack Rose": "Jack Rose (guitarist)",
  "Jackie Edwards": "Jackie Edwards (musician)",
  "Jackie Moore": "Jackie Moore (singer)",
  "Jackie Ward": "Robin Ward (singer)",
  "Jacob Miller": "Jacob Miller (musician)",
  "Jade": "Jade (producer)",
  "Jakarta": "Jakarta (DJs)",
  "Jakatta": "Dave Lee (DJ)",
  "James Blake": "James Blake (musician)",
  "James Carr": "James Carr (singer)",
  "James Davis": "James B. Davis (musician)",
  "James Dewar": "James Dewar (musician)",
  "James Dillon": "James Dillon (composer)",
  "James Hand": "James Hand (musician)",
  "James Hendricks": "Jim Hendricks (musician)",
  "James Holden": "James Holden (producer)",
  "James Hook": "James Hook (composer)",
  "James House": "James House (singer)",
  "James Hunter": "James Hunter (singer)",
  "James Montgomery Band": "James Montgomery (singer)",
  "James Moody": "James Moody (saxophonist)",
  "Jamie Fielding": "Jamie Fielding (musician)",
  "Jammer": "Jammer (musician)",
  "Jann": "Jann (singer)",
  "Jaroslav Ježek": "Jaroslav Ježek (composer)",
  "Jasmine Sagginario": "Jasmine (American singer)",
  "Jason Hill": "Jason Hill (singer)",
  "Jason Moran": "Jason Moran (musician)",
  "Jason Robinson": "Jason Robinson (musician)",
  "Jason Ross": "Jason Ross (musician)",
  "Jeckyll & Hyde": "Jeckyll & Hyde (musicians)",
  "Jeff Ballard": "Jeff Ballard (musician)",
  "Jeff Black": "Jeff Black (musician)",
  "Jeff Hamilton": "Jeff Hamilton (drummer)",
  "Jeff Johnson": "Jeff Johnson (musician)",
  "Jeff Parker": "Jeff Parker (musician)",
  "Jeff Simmons": "Jeff Simmons (musician)",
  "Jega": "Jega (musician)",
  "Jeremy Lee 李駿傑": "Jeremy Lee (singer)",
  "Jerry Jerome": "Jerry Jerome (saxophonist)",
  "Jerry Martin": "Jerry Martin (composer)",
  "Jesse Johnson": "Jesse Johnson (musician)",
  "Jesse Welles": "Jesse Welles (musician)",
  "Jessi": "Jessi (musician)",
  "Jessica Pratt": "Jessica Pratt (musician)",
  "Jewel": "Jewel (singer)",
  "Jill Scott": "Jill Scott (singer)",
  "Jim Ford": "Jim Ford (singer-songwriter)",
  "Jim Guthrie": "Jim Guthrie (singer-songwriter)",
  "Jim Hall": "Jim Hall (musician)",
  "Jim McIntyre": "Jim McIntyre (musician)",
  "Jim Messina": "Jim Messina (musician)",
  "Jim O'Rourke": "Jim O'Rourke (musician)",
  "Jim White": "Jim White (guitarist)",
  "Jimmy Davis": "Jimmy Davis (songwriter)",
  "Jimmy Forrest": "Jimmy Forrest (musician)",
  "Jimmy Hughes": "Jimmy Hughes (singer)",
  "Jimmy Hunt": "Jimmy Hunt (musician)",
  "Jimmy Jones": "Jimmy Jones (singer)",
  "Jimmy Owens": "Jimmy Owens (musician)",
  "Jimmy Smith": "Jimmy Smith (musician)",
  "Jini": "Jini (singer)",
  "Jinu": "Kim Jin-woo (musician)",
  "Joaquina": "Joaquina (musician)",
  "Jodi": "Jodi (musician)",
  "Joe": "Joe (singer)",
  "Joe Buck": "Joe Buck (musician)",
  "Joe Carroll": "Joe Carroll (singer)",
  "Joe Egan": "Joe Egan (musician)",
  "Joe English": "Joe English (musician)",
  "Joe Ford": "Joe Ford (musician)",
  "Joe Gibbs": "Joe Gibbs (record producer)",
  "Joe Goddard": "Joe Goddard (musician)",
  "Joe Gordon": "Joe Gordon (musician)",
  "Joe Hicks": "Joe Hicks (musician)",
  "Joe Jackson": "Joe Jackson (musician)",
  "Joe Morris": "Joe Morris (guitarist)",
  "Joe O'Donnell": "Joe O'Donnell (musician)",
  "Joe Perry": "Joe Perry (musician)",
  "Joe Simon": "Joe Simon (musician)",
  "Joe White": "Joe White (singer)",
  "Joe Wong": "Joe Wong (musician)",
  "Johann Christoph Vogel": "Johann Vogel (composer)",
  "John '00' Fleming": "John Fleming (DJ)",
  "John Abercrombie": "John Abercrombie (guitarist)",
  "John Adams": "John Adams (composer)",
  "John Anthony": "John Anthony (record producer)",
  "John Browne": "John Browne (composer)",
  "John Bull": "John Bull (composer)",
  "John Bush": "John Bush (singer)",
  "John Butcher": "John Butcher (musician)",
  "John Cameron": "John Cameron (musician)",
  "John Craigie": "John Craigie (musician)",
  "John Davis": "John Davis (singer)",
  "John Doe and The Sadies": "John Doe (musician)",
  "John Eccles": "John Eccles (composer)",
  "John Ellis": "John Ellis (saxophonist)",
  "John Fahey": "John Fahey (musician)",
  "John Farmer": "John Farmer (composer)",
  "John Field": "John Field (composer)",
  "John Fischer": "John Fischer (pianist)",
  "John Grant": "John Grant (musician)",
  "John Greaves": "John Greaves (musician)",
  "John Gustafson": "John Gustafson (musician)",
  "John Hackett": "John Hackett (musician)",
  "John Hicks": "John Hicks (pianist)",
  "John Holt": "John Holt (singer)",
  "John Howard & The Night Mail": "John Howard (musician)",
  "John Ireland": "John Ireland (composer)",
  "John K.": "John K (musician)",
  "John Kay": "John Kay (musician)",
  "John Kirby": "John Kirby (musician)",
  "John Lewis": "John Lewis (pianist)",
  "John Mackey": "John Mackey (composer)",
  "John McCabe": "John McCabe (composer)",
  "John McCarthy": "John McCarthy (conductor)",
  "John McLaughlin": "John McLaughlin (musician)",
  "John Metcalfe": "John Metcalfe (composer)",
  "John Miles": "John Miles (musician)",
  "John Mooney": "John Mooney (musician)",
  "John Murphy": "John Murphy (musician)",
  "John Patton": "John Patton (musician)",
  "John Paul Jones": "John Paul Jones (musician)",
  "John Phillips": "John Phillips (musician)",
  "John Power": "John Power (musician)",
  "John Rimmer": "John Rimmer (composer)",
  "John Sheppard": "John Sheppard (composer)",
  "John Southworth": "John Southworth (musician)",
  "John Walker": "John Walker (musician)",
  "John Ward": "John Ward (composer)",
  "John Wesley Harding": "John Wesley Harding (singer)",
  "John Williamson": "John Williamson (singer)",
  "Johnnie Johnson": "Johnnie Johnson (musician)",
  "Johnny Fuller": "Johnny Fuller (musician)",
  "Johnny Harris": "Johnny Harris (musician)",
  "Johnny Jones And The King Casuals": "Johnny Jones (musician)",
  "Johnny Rebel": "Johnny Rebel (singer)",
  "Johnny Ringo": "Johnny Ringo (musician)",
  "Johnny Thunder": "Johnny Thunder (singer)",
  "Joji": "Joji (musician)",
  "Jon Christensen": "Jon Christensen (musician)",
  "Jon Cleary": "Jon Cleary (musician)",
  "Jon Cutler": "Jon Cutler (musician)",
  "Jon Snodgrass": "Jon Snodgrass (musician)",
  "Jonathan Harvey": "Jonathan Harvey (composer)",
  "Jonathan Nelson": "Jonathan Nelson (singer)",
  "Jonathan Wilson": "Jonathan Wilson (musician)",
  "Jones": "Jones (singer)",
  "Joseph Israel": "Joseph Israel (musician)",
  "Joseph Spence": "Joseph Spence (musician)",
  "Joseph Williams": "Joseph Williams (musician)",
  "Josh Wilson": "Josh Wilson (musician)",
  "Joshua Abrams": "Joshua Abrams (musician)",
  "José Padilla": "José Padilla (DJ)",
  "Juan Carlos Godoy": "Juan Carlos Godoy (singer)",
  "Juan Maglio": "Juan Maglio (musician)",
  "Juan Pablo Torres": "Juan Pablo Torres (musician)",
  "Judy Bailey": "Judy Bailey (pianist)",
  "Julia Wu": "Julia Wu (singer)",
  "Julian Brandt": "Julian Brandt (artist)",
  "Julius Fučík": "Julius Fučík (composer)",
  "Justin Lanning": "Justin Lanning (musician)",
  "KEVIN MCKAY": "Kevin McKay (musician)",
  "KILLY": "Killy (rapper)",
  "KLP": "KLP (musician)",
  "Kapo!": "Kapo (singer)",
  "Karen Brooks": "Karen Brooks (singer)",
  "Karizma": "Karizma (musician)",
  "Kashif": "Kashif (musician)",
  "Katalyst": "Katalyst (musician)",
  "Kate Miner": "Kate Miner (musician)",
  "Kate Westbrook": "Kate Westbrook (musician)",
  "Katharine Blake": "Katharine Blake (singer)",
  "Kathryn Scott": "Kathryn Scott (singer)",
  "Katrin Mokko": "Mot (rapper)",
  "Kavana": "Kavana (singer)",
  "Kay Adams": "Kay Adams (singer)",
  "KeBu": "Kebu (musician)",
  "Keith Scott": "Keith Scott (musician)",
  "Kelly Moran": "Kelly Moran (musician)",
  "Kem": "Kem (singer)",
  "Ken Kelly": "Ken Kelly (artist)",
  "Ken Parker": "Ken Parker (musician)",
  "Ken Pomeroy": "Ken Pomeroy (singer)",
  "Kevin Gilbert": "Kevin Gilbert (musician)",
  "Khayat": "Khayat (singer)",
  "Khotin": "Khotin (musician)",
  "Kid Frost": "Frost (rapper)",
  "Kilowatts": "KiloWatts (musician)",
  "Kim Jae Hwan": "Kim Jae-hwan (singer)",
  "Kim Robertson": "Kim Robertson (musician)",
  "Kindness": "Kindness (musician)",
  "King Khan": "King Khan (musician)",
  "King Kong": "King Kong (musician)",
  "Kito": "Kito (musician)",
  "Klaas": "Klaas (DJ)",
  "Klein": "Klein (musician)",
  "Klute": "Klute (musician)",
  "Knucks": "Knucks (musician)",
  "Kodomo": "Kodomo (musician)",
  "Kofi": "Kofi (musician)",
  "Kompany": "Kompany (musician)",
  "Kreng": "Kreng (musician)",
  "Kretan": "Blanke (DJ)",
  "Krish": "Krish (singer)",
  "Krishna Das": "Krishna Das (singer)",
  "Kuren": "Kuren (singer)",
  "Kölsch": "Kölsch (musician)",
  "L'Orange": "L'Orange (record producer)",
  "LV": "L.V. (singer)",
  "Ladyhawke": "Ladyhawke (musician)",
  "Lamar Campbell": "Lamar Campbell (musician)",
  "Lanny Huang": "Andrew Huang (musician)",
  "Larry Collins": "Larry Collins (guitarist)",
  "Larry Harlow": "Larry Harlow (musician)",
  "Larry Marshall": "Larry Marshall (singer)",
  "Larry Young": "Larry Young (musician)",
  "Latimore": "Latimore (musician)",
  "Laufey": "Laufey (singer)",
  "Laurence Jones": "Laurence Jones (musician)",
  "Lee Minhyuk": "Lee Min-hyuk (rapper, born 1990)",
  "Leo Graham": "Leo Graham (songwriter)",
  "Leonard Dillon": "Christopher Martin (singer)",
  "Leroy Foster": "Leroy Foster (musician)",
  "Leroy Jenkins": "Leroy Jenkins (musician)",
  "Leslie Howard": "Leslie Howard (musician)",
  "Lewis Parker": "Lewis Parker (musician)",
  "Lexa": "Lexa (singer)",
  "Lexy": "Lexy (singer)",
  "Lido": "Lido (musician)",
  "Linda Hayes": "Linda Hayes (singer)",
  "Linda Thompson": "Linda Thompson (singer)",
  "Lindell": "Lindell (musician)",
  "Liquid": "Liquid (musician)",
  "Lisa Hilton": "Lisa Hilton (musician)",
  "Lithe": "Lithe (singer)",
  "Little Ann": "Little Ann (singer)",
  "Little Joe": "Little Joe (singer)",
  "Little John": "Little John (musician)",
  "Little Johnny Jones": "Little Johnny Jones (pianist)",
  "Lloyd": "Lloyd (singer)",
  "Logistics": "Logistics (musician)",
  "Lola Young": "Lola Young (singer)",
  "Lone Ranger": "Lone Ranger (musician)",
  "Lonnie Johnson": "Lonnie Johnson (musician)",
  "Loon": "Loon (rapper)",
  "Loop Da Loop": "Space Cowboy (musician)",
  "Lorn": "Lorn (musician)",
  "Lorna": "Lorna (rapper)",
  "Lost Stories": "Lost Stories (DJs)",
  "Lou Johnson": "Lou Johnson (singer)",
  "Lou Levy": "Lou Levy (pianist)",
  "Lou Perez": "Lou Perez (musician)",
  "Louis Philippe": "Louis Philippe (musician)",
  "Louis Smith": "Louis Smith (musician)",
  "Louis The Child": "Louis the Child (DJs)",
  "Luana": "Luana (singer)",
  "Luciana": "Luciana (singer)",
  "Luciano": "Luciano (DJ)",
  "Lucky Luciano": "Lucky Luciano (rapper)",
  "Luis Días": "Luis Días (composer)",
  "Luis Enrique": "Luis Enrique (singer)",
  "Luis Perdomo": "Luis Perdomo (pianist)",
  "Luis Vargas": "Luis Vargas (musician)",
  "Luke Steele": "Luke Steele (musician)",
  "Lulu": "Lulu (singer)",
  "Lunay": "Lunay (singer)",
  "Lynn Morris": "Lynn Morris (musician)",
  "Maes": "Maes (rapper)",
  "Maino": "Maino (rapper)",
  "Major Harris": "Major Harris (singer)",
  "Makhadzi": "Makhadzi (singer)",
  "Makoto": "Makoto (musician)",
  "Malente": "Malente (DJ)",
  "Mali Music": "Mali Music (singer)",
  "Malia": "Malia (singer)",
  "Mamer": "Mamer (musician)",
  "Manitoba": "Caribou (musician)",
  "Manse": "Manse (DJ)",
  "Manuel Carrasco": "Manuel Carrasco (singer)",
  "Marc Kinchen": "MK (DJ)",
  "Marc Nelson": "Marc Nelson (singer)",
  "Marcin Wasilewski": "Marcin Wasilewski (pianist)",
  "Maria Rivas": "María Rivas (singer)",
  "Maria Schneider": "Maria Schneider (musician)",
  "Marika": "Marika (singer)",
  "Mario Ochoa": "Mario Ochoa (DJ)",
  "Marion Williams": "Marion Williams (singer)",
  "Marisela": "Marisela (singer)",
  "Mark Atkins": "Mark Atkins (musician)",
  "Mark Fell": "Mark Fell (artist)",
  "Mark Harris": "Mark Harris (musician)",
  "Mark Hollis": "Mark Hollis (musician)",
  "Mark Kendall": "Mark Kendall (guitarist)",
  "Mark Murphy": "Mark Murphy (singer)",
  "Mark O'Leary": "Mark O'Leary (musician)",
  "Mark Pritchard": "Mark Pritchard (musician)",
  "Mark Selby": "Mark Selby (musician)",
  "Mark Turner": "Mark Turner (musician)",
  "Mark Williams": "Mark Williams (singer)",
  "Marlon Williams": "Marlon Williams (musician)",
  "Marque": "Marque (musician)",
  "Marshall Hall": "Marshall Hall (singer)",
  "Martin Harley": "Martin Harley (musician)",
  "Martin Jensen": "Martin Jensen (DJ)",
  "Martin Newell": "Martin Newell (musician)",
  "Marty": "Marty (rapper)",
  "Martyn": "Martyn (musician)",
  "Mary McBride": "Mary McBride (musician)",
  "Mary O'Hara": "Mary O'Hara (singer)",
  "María Rivas": "María Rivas (singer)",
  "Masego": "Masego (musician)",
  "Masoud": "Masoud (musician)",
  "Mateo Romero": "Mateo Romero (composer)",
  "Matt Elliott": "Matt Elliott (musician)",
  "Matt Johnson": "Matt Johnson (singer)",
  "Matt Mitchell": "Matt Mitchell (pianist)",
  "Matt Slocum": "Matt Slocum (drummer)",
  "Matthew Fisher": "Matthew Fisher (musician)",
  "Matthew Parker": "Matthew Parker (singer)",
  "Matthew Stevens": "Matthew Stevens (musician)",
  "Matthew Ward": "Matthew Ward (singer)",
  "Maurice Greene": "Maurice Greene (composer)",
  "Maxwell": "Maxwell (musician)",
  "Meck": "Meck (musician)",
  "Medina": "Medina (singer)",
  "Medlar": "Medlar (musician)",
  "Medway": "Medway (DJ)",
  "Mel Brown": "Mel Brown (guitarist)",
  "Mel Walker": "Mel Walker (musician)",
  "Mellow Mark": "Pinchers (singer)",
  "Meng Jia": "Jia (singer)",
  "Merlin": "Merlin (rapper)",
  "Merrill Moore": "Merrill Moore (musician)",
  "Michael Anthony": "Michael Anthony (musician)",
  "Michael Blake": "Michael Blake (musician)",
  "Michael Bradley": "Michael Bradley (singer)",
  "Michael Clarke": "Michael Clarke (musician)",
  "Michael English": "Michael English (singer)",
  "Michael Fennelly": "Michael Fennelly (musician)",
  "Michael Franks": "Michael Franks (musician)",
  "Michael Gray": "Michael Gray (DJ)",
  "Michael Gregory Jackson": "Michael Gregory (guitarist)",
  "Michael Head & The Red Elastic Band": "Michael Head (musician)",
  "Michael Hurley": "Michael Hurley (musician)",
  "Michael Marshall": "Michael Marshall (singer)",
  "Michael Mayer": "Michael Mayer (musician)",
  "Michael McDonald": "Michael McDonald (musician)",
  "Michael Rose": "Michael Rose (singer)",
  "Michael White": "Michael White (violinist)",
  "Michel Godard": "Michel Godard (musician)",
  "Michelle Williams": "Michelle Williams (singer)",
  "Mighty Joe Young": "Mighty Joe Young (musician)",
  "Mike Brooks": "Mike Brooks (singer)",
  "Mike Hawkins": "Mike Hawkins (musician)",
  "Mike Kelley": "Mike Kelley (artist)",
  "Mike Skinner": "Mike Skinner (musician)",
  "Miki": "Miki (artiste)",
  "Milet": "Milet (singer)",
  "Miller Anderson": "Miller Anderson (musician)",
  "Ming & FS": "Ming (DJ)",
  "Mishka": "Mishka (musician)",
  "Miz": "Miz (singer)",
  "Moana": "Moana (singer)",
  "Moein": "Moein (singer)",
  "Mokhov": "Mokhov (musician)",
  "Momus": "Momus (musician)",
  "Monica": "Monica (singer)",
  "Moon Honey": "Samia (musician)",
  "Mora": "Mora (singer)",
  "Moyka": "Moyka (singer)",
  "Munchi": "Munchi (DJ)",
  "Muro": "Muro (DJ)",
  "Murs": "Murs (rapper)",
  "Muscles": "Muscles (musician)",
  "Muzi": "Muzi (musician)",
  "Muzzy": "Muzz (musician)",
  "Myd": "Myd (musician)",
  "NAPT": "NAPT (DJs)",
  "NAV": "Nav (rapper)",
  "NF": "NF (rapper)",
  "Nadia Ali": "Nadia Ali (singer)",
  "Naldo": "Naldo (producer)",
  "Natalie Brown": "Natalie Brown (singer)",
  "Natasha Barrett": "Natasha Barrett (composer)",
  "Natasha Thomas": "Natasha Thomas (singer)",
  "Nathan Johnson": "Nathan Johnson (musician)",
  "Nava": "Nava (musician)",
  "Naza": "Naza (rapper)",
  "Neal Smith": "Neal Smith (drummer)",
  "Neckle Camp": "Jammer (musician)",
  "Necro": "Necro (rapper)",
  "Nesty La Mente Maestra": "Nesty (producer)",
  "Netsky": "Netsky (musician)",
  "Nicole Mitchell": "Nicole Mitchell (musician)",
  "Nicolette": "Nicolette (musician)",
  "Nigel Hall": "Nigel Hall (musician)",
  "Nigga": "Flex (singer)",
  "Niko": "Niko (musician)",
  "Nikola Gala": "Gala (singer)",
  "Nils Landgren": "Nils Landgren (musician)",
  "Nils Landgren Funk Unit": "Nils Landgren (musician)",
  "Nils Økland": "Nils Økland (musician)",
  "Nines": "Nines (rapper)",
  "Niska": "Niska (rapper)",
  "Nitrouz": "Outbreak (DJ)",
  "Nitti": "Nitti (producer)",
  "Nneka": "Nneka (singer)",
  "Noel Robinson": "Noel Robinson (musician)",
  "Nondi_": "Nondi (musician)",
  "Noriega": "Noriega (producer)",
  "Norman Brown": "Norman Brown (guitarist)",
  "Norman Harris": "Norman Harris (musician)",
  "Norman O'Neill": "Norman O'Neill (composer)",
  "North West": "North West (musician)",
  "Notch": "Notch (musician)",
  "Novelist": "Novelist (musician)",
  "Nuuro": "Arca (musician)",
  "Ochre": "Ochre (musician)",
  "Odete": "Odete (artista)",
  "Ofenbach & Nick Waterhouse": "Ofenbach (DJs)",
  "Oh No": "Oh No (musician)",
  "Ole Olsen": "Ole Olsen (composer)",
  "Oliver": "Oliver (DJs)",
  "Oliver Wilde": "Oliver Wilde (musician)",
  "Olivia": "Olivia (singer)",
  "Olympe": "Olympe (singer)",
  "Omni Trio": "Robert Haigh (musician)",
  "Organum": "David Jackman (musician)",
  "Oscar Lopez": "Óscar López (guitarist)",
  "Otis Taylor": "Otis Taylor (musician)",
  "Ott": "Ott (record producer)",
  "Otto": "Otto (singer)",
  "Owen-": "Owen (musician)",
  "Owsley": "Owsley (musician)",
  "Oxlade": "Oxlade (singer)",
  "PBK": "PBK (composer)",
  "PHILIP GEORGE": "Philip George (DJ)",
  "Paces": "Paces (musician)",
  "Panama disco lights": "Lights (musician)",
  "Panda Bear": "Panda Bear (musician)",
  "Paperboy": "Paperboy (rapper)",
  "Paradox": "Paradox (musician)",
  "Parasite": "Parasite (musician)",
  "Pat Kelly": "Pat Kelly (musician)",
  "Patra": "Patra (singer)",
  "Patrick Watson": "Patrick Watson (musician)",
  "Paul Bryan": "Paul Bryan (musician)",
  "Paul Clayton": "Paul Clayton (singer)",
  "Paul Collins": "Paul Collins (musician)",
  "Paul Evans": "Paul Evans (musician)",
  "Paul Harrington": "Paul Harrington (musician)",
  "Paul Horn": "Paul Horn (musician)",
  "Paul Johnson": "Paul Johnson (producer)",
  "Paul Jones": "Paul Jones (singer)",
  "Paul Lamb": "Paul Lamb (musician)",
  "Paul Parker": "Paul Parker (singer)",
  "Paul Ryan": "Paul Ryan (singer)",
  "Paul Schwartz": "Paul Schwartz (composer)",
  "Paul Winter": "Paul Winter (violinist)",
  "Paul Woolford": "Paul Woolford (DJ)",
  "Paulina": "Paulina (singer)",
  "Paulo Ricardo": "Paulo Ricardo (musician)",
  "Peaches": "Peaches (musician)",
  "Pebbles": "Pebbles (musician)",
  "Peekaboo": "Peekaboo (musician)",
  "People Like Us": "People Like Us (musician)",
  "Percy Jones": "Percy Jones (musician)",
  "Perquisite": "Perquisite (musician)",
  "Peruzzi": "Peruzzi (singer)",
  "Pete Johnson": "Pete Johnson (musician)",
  "Pete Swanson": "Pete Swanson (musician)",
  "Peter Bernstein Trio": "Peter Bernstein (guitarist)",
  "Peter Evans Quintet": "Peter Evans (musician)",
  "Peter Garland": "Peter Garland (composer)",
  "Peter Godwin": "Peter Godwin (singer)",
  "Peter Gordon": "Peter Gordon (composer)",
  "Peter Graham": "Peter Graham (composer)",
  "Peter Leitch": "Peter Leitch (musician)",
  "Peter Murphy": "Peter Murphy (musician)",
  "Petter": "Petter (artist)",
  "Pez": "Pez (musician)",
  "Phew": "Phew (singer)",
  "Phil Hewson": "Dave Hewson (composer)",
  "Phillip Walker": "Phillip Walker (musician)",
  "Phosphorescent": "Phosphorescent (musician)",
  "Pilote": "Pilote (musician)",
  "Pinch": "Pinch (drummer)",
  "Pink": "Pink (singer)",
  "Pitbull": "Pitbull (rapper)",
  "Plies": "Plies (rapper)",
  "Plumb": "Plumb (singer)",
  "Poe": "Poe (singer)",
  "Pogo": "Pogo (musician)",
  "Polar": "Polar (musician)",
  "Pole": "Pole (musician)",
  "Pongo": "Pongo (musician)",
  "Poppy": "Poppy (singer)",
  "Presence": "Charles Webster (musician)",
  "Pressa": "Pressa (rapper)",
  "Prince": "Prince (musician)",
  "Prince Club": "Prince (musician)",
  "Prodigy": "Prodigy (rapper)",
  "Pyhimys": "Pyhimys (artisti)",
  "Q-Tip": "Q-Tip (musician)",
  "QUINTINO": "Quintino (DJ)",
  "Quantic": "Quantic (musician)",
  "Queen Omega": "Queen Omega (singer)",
  "Quevedo": "Quevedo (singer)",
  "Quilla": "Quilla (musician)",
  "Quinn Sullivan": "Quinn Sullivan (musician)",
  "Quivver": "John Graham (producer)",
  "ROLAND CLARK": "Roland Clark (DJ)",
  "ROUTE 94": "Route 94 (musician)",
  "Rabbi Shlomo Carlebach": "Shlomo Carlebach (musician)",
  "Radio Slave": "Matt Edwards (DJ)",
  "Raissa": "Raissa (singer, born 1971)",
  "Raja Ram": "Raja Ram (musician)",
  "Rake": "Rake (singer)",
  "Ramirez": "Ramirez (rapper)",
  "Ramz": "Ramz (rapper)",
  "Randolph": "Paul Randolph (musician)",
  "Randy Wood": "Randy Wood (producer)",
  "Ras Attitude": "Pliers (singer)",
  "Ras Michael & The Sons Of Negus": "Red Dragon (musician)",
  "Ravi": "Ravi (rapper)",
  "Ray Anderson": "Ray Anderson (musician)",
  "Ray Brown": "Ray Brown (musician)",
  "Ray Crawford": "Ray Crawford (musician)",
  "Ray Fisher": "Ray Fisher (singer)",
  "Ray Russell": "Ray Russell (musician)",
  "Ray Wilson": "Ray Wilson (musician)",
  "Rebecca Clarke": "Rebecca Clarke (composer)",
  "Rebecca Ferguson": "Rebecca Ferguson (singer)",
  "Rebekah": "Rebekah (DJ)",
  "Redlight": "Redlight (musician)",
  "Redman": "Redman (rapper)",
  "Reese Antoinette": "Antoinette (rapper)",
  "Regard": "Regard (DJ)",
  "Regis": "Regis (musician)",
  "Reinhard Voigt": "Reinhard Voigt (musician)",
  "Rema": "Rema (musician)",
  "Rene Lopez": "Rene Lopez (musician)",
  "René Thomas": "René Thomas (guitarist)",
  "Reol": "Reol (singer)",
  "Req": "REQ (musician)",
  "Rev. James Moore": "James Moore (singer)",
  "Rhodri Davies": "Rhodri Davies (musician)",
  "Richard & Linda Thompson": "Richard Thompson (musician)",
  "Richard Barnes": "Richard Barnes (musician)",
  "Richard Barrett": "Richard Barrett (composer)",
  "Richard Berry": "Richard Berry (musician)",
  "Richard Buckner": "Richard Buckner (musician)",
  "Richard Butler": "Richard Butler (singer)",
  "Richard Carpenter": "Richard Carpenter (musician)",
  "Richard Dawson": "Richard Dawson (musician)",
  "Richard Johnston": "Richard Johnston (musician)",
  "Richard Lloyd": "Richard Lloyd (guitarist)",
  "Richard Müller": "Richard Müller (singer)",
  "Richard Page": "Richard Page (musician)",
  "Richard Ramirez": "Richard Ramirez (musician)",
  "Richard Smallwood": "Richard Smallwood (musician)",
  "Richard Swift": "Richard Swift (musician)",
  "Richard Thompson": "Richard Thompson (musician)",
  "Richard Wells": "Richard Wells (composer)",
  "Richard Wright": "Richard Wright (musician)",
  "Rick Roberts": "Rick Roberts (musician)",
  "Ricky Bell": "Ricky Bell (singer)",
  "Rico Rodriguez": "Rico Rodriguez (musician)",
  "Rik Rok": "John Holt (singer)",
  "Riton": "Riton (musician)",
  "River Tiber": "River Tiber (musician)",
  "RoRo": "RoRo (singer)",
  "Rob Thomas": "Rob Thomas (musician)",
  "Robert Ballard": "Robert Ballard (composer)",
  "Robert Finley": "Robert Finley (musician)",
  "Robert Fuchs": "Robert Fuchs (composer)",
  "Robert Knight": "Robert Knight (musician)",
  "Robert Lucas": "Robert Lucas (musician)",
  "Robert Morton": "Robert Morton (composer)",
  "Robert Owens": "Robert Owens (musician)",
  "Robert Palmer": "Robert Palmer (singer)",
  "Robert Parker": "Robert Parker (singer)",
  "Robert Parsons": "Robert Parsons (composer)",
  "Robert Post": "Robert Post (musician)",
  "Robert W. Smith": "Robert W. Smith (musician)",
  "Roberto Torres": "Roberto Torres (musician)",
  "Rocca": "Rocca (rapper)",
  "Rockwell": "Rockwell (musician)",
  "Rod Taylor": "Rod Taylor (singer)",
  "Roger Nichols Trio": "Roger Nichols (songwriter)",
  "Romain Virgo": "C-Real (rapper)",
  "Ron Davies": "Ron Davies (songwriter)",
  "Ron Elliott": "Ron Elliott (musician)",
  "Rone": "Rone (musician)",
  "Ronnie Jones": "Ronnie Jones (singer)",
  "Roscoe Robinson": "Roscoe Robinson (musician)",
  "Roser": "Roser (singer)",
  "Ross Edwards": "Ross Edwards (composer)",
  "Rosé": "Rosé (singer)",
  "Roy Hall": "Roy Hall (musician)",
  "Roy Harper": "Roy Harper (singer)",
  "Rubén González": "Rubén González (pianist)",
  "Ruel": "Ruel (singer)",
  "Rui Da Silva": "Rui da Silva (DJ)",
  "Rumer": "Rumer (musician)",
  "Rupee": "Rupee (musician)",
  "Rusko": "Rusko (musician)",
  "Russ Freeman": "Russ Freeman (pianist)",
  "Rvfv": "Rvfv (singer)",
  "Ryan Stevenson": "Ryan Stevenson (singer)",
  "SLANDER": "Slander (DJs)",
  "Saigon": "Saigon (rapper)",
  "Saint Raymond": "Saint Raymond (musician)",
  "Saint Saviour": "Saint Saviour (musician)",
  "Salmo": "Salmo (rapper)",
  "Sam Barber": "Sam Barber (singer)",
  "Sam Cohen": "Sam Cohen (musician)",
  "Sam Collins": "Sam Collins (musician)",
  "Sam Fletcher": "Sam Fletcher (singer)",
  "Sam Harris": "Sam Harris (singer)",
  "Sam Jones": "Sam Jones (musician)",
  "Samantha Lam": "Samantha Lam (singer)",
  "Sampaguita": "Sampaguita (singer)",
  "Samuel Arnold": "Samuel Arnold (composer)",
  "Sana": "Sana (singer)",
  "Sanah": "Sanah (singer)",
  "Sandro Silva": "Sandro Silva (DJ)",
  "Sango": "Sango (musician)",
  "Santiago Salazar": "Santiago Salazar (musician)",
  "Sapho": "Sapho (singer)",
  "Sara Lee": "Sara Lee (musician)",
  "Sarsa": "Sarsa (singer)",
  "Sasha": "Sasha (DJ)",
  "Sasse": "Sasse (musician)",
  "Sati": "Sati (singer)",
  "Satoshi": "Satoshi (singer)",
  "Savant": "Savant (musician)",
  "Sawa": "Sawa (singer)",
  "Sayuri": "Sayuri (musician)",
  "Scanty Sandwich": "Richard Marshall (DJ)",
  "Scientist": "Scientist (musician)",
  "Scorcher": "Scorcher (rapper)",
  "Scott Engel": "Scott Walker (singer)",
  "Scott Kelly": "Scott Kelly (musician)",
  "Scott Reeder": "Scott Reeder (bassist)",
  "Scott Walker": "Scott Walker (singer)",
  "Seagram": "Seagram (rapper)",
  "Seal": "Seal (musician)",
  "Sean Henry": "Sean Henry (musician)",
  "Sean Rowe": "Sean Rowe (musician)",
  "Seba": "Seba (musician)",
  "Sech": "Sech (singer)",
  "Self Esteem": "Self Esteem (musician)",
  "Selwyn": "Selwyn (singer)",
  "Senhit": "Senhit (singer)",
  "Sensational": "Sensational (musician)",
  "Serengeti": "Serengeti (rapper)",
  "ShaSimone": "Redlight (musician)",
  "Shackleton": "Shackleton (musician)",
  "Shaggy": "Shaggy (musician)",
  "Shake": "Shake (singer)",
  "Shamir": "Shamir (musician)",
  "Shani": "Shani (singer)",
  "Sharda": "Sharda (singer)",
  "Shaun": "Shaun (musician)",
  "Shaun Baker": "Shaun Baker (musician)",
  "Shaun Murphy": "Shaun Murphy (singer)",
  "Shawn Lee": "Shawn Lee (musician)",
  "She Rockers": "Slacker (producer)",
  "Sheila Walsh": "Sheila Walsh (singer)",
  "Sheng": "Sheng (musician)",
  "Shifted Phases": "James Stinson (musician)",
  "Shigeto": "Shigeto (musician)",
  "Siba": "Siba (singer)",
  "Sid Phillips": "Sid Phillips (musician)",
  "Sidney Barnes": "Sidney Barnes (musician)",
  "Sido": "Sido (rapper)",
  "Sigma": "Sigma (DJs)",
  "Sigrid": "Sigrid (singer)",
  "Silkie": "Silkie (musician)",
  "Simon Curtis": "Simon Curtis (singer)",
  "Simon Finn": "Simon Finn (musician)",
  "Simon Phillips": "Simon Phillips (drummer)",
  "Sinclair": "Sinclair (singer)",
  "Sir Henry Wood": "Henry Wood (conductor)",
  "Sir Richard Bishop": "Richard Bishop (guitarist)",
  "Sirone": "Sirone (musician)",
  "Sleezy D.": "Derrick Harris (musician)",
  "Slug": "Slug (rapper)",
  "Sluggo": "Dave Katz (songwriter)",
  "Snail Mail": "Snail Mail (musician)",
  "Snails": "Snails (DJ)",
  "Snooze": "Snooze (musician)",
  "Solar Gods": "Distance (musician)",
  "Solvent": "Solvent (producer)",
  "Sonique": "Sonique (musician)",
  "Sonny & The Sunsets": "Sonny Smith (musician)",
  "SooBin": "Soobin (singer)",
  "Sophie May": "Sophie May (singer)",
  "Sori": "Sori (singer)",
  "Space Manoeuvres": "John Graham (producer)",
  "Spyro": "Spyro (musician)",
  "St. Lucia": "St. Lucia (musician)",
  "St. Vincent": "St. Vincent (musician)",
  "Stephen Bishop": "Stephen Bishop (singer)",
  "Steve Anderson": "Steve Anderson (musician)",
  "Steve Bell": "Steve Bell (musician)",
  "Steve Davis": "Steve Davis (bassist)",
  "Steve Edwards": "Steve Edwards (singer)",
  "Steve Grand": "Steve Grand (musician)",
  "Steve Gunn": "Steve Gunn (musician)",
  "Steve Harris": "Steve Harris (musician)",
  "Steve Lacy": "Steve Lacy (musician)",
  "Steve Lawler": "Steve Lawler (DJ)",
  "Steve Lehman": "Steve Lehman (composer)",
  "Steve Miller": "Steve Miller (musician)",
  "Steve Roach": "Steve Roach (musician)",
  "Steve Stoll and Mike MC Coy": "Steve Stoll (musician)",
  "Steve Walsh": "Steve Walsh (musician)",
  "Steve White": "Steve White (drummer)",
  "Stevie Woods": "Stevie Woods (musician)",
  "Stig Of The Dump": "Stig of the Dump (rapper)",
  "Stimming": "Stimming (musician)",
  "Sting": "Sting (musician)",
  "StoneBridge": "StoneBridge (DJ)",
  "Stonewall Jackson": "Stonewall Jackson (musician)",
  "Storm Queen": "Storm Queen (musician)",
  "Stuart Davis": "Stuart Davis (musician)",
  "Stuart Sherman": "Stuart Sherman (artist)",
  "Styrofoam": "Styrofoam (musician)",
  "Suavé": "Suave (singer)",
  "Submerged": "Submerged (DJ)",
  "Sunny": "Sunny (singer)",
  "Suran": "Suran (singer)",
  "Surgeon": "Surgeon (DJ)",
  "Susan Osborn": "Susan Osborn (musician)",
  "Susana Guerra": "Suzy (singer)",
  "Sybarite": "Sybarite (musician)",
  "Sylvester Weaver": "Sylvester Weaver (musician)",
  "Sylvia Syms": "Sylvia Syms (singer)",
  "Sıla": "Sıla (singer)",
  "Taffy": "Taffy (singer)",
  "Taj Mahal": "Taj Mahal (musician)",
  "Tanith": "Tanith (DJ)",
  "Tarkan": "Tarkan (singer)",
  "Ted Lewis & His Band": "Ted Lewis (musician)",
  "Ted Nash": "Ted Nash (saxophonist, born 1960)",
  "Tei": "Tei (singer)",
  "Tekno": "Tekno (musician)",
  "Tempo": "Tempo (rapper)",
  "Teoman": "Teoman (singer)",
  "Terry Allen": "Terry Allen (artist)",
  "Terry Evans": "Terry Evans (musician)",
  "Terry Jennings": "Terry Jennings (composer)",
  "Teruo Nakamura": "Teruo Nakamura (musician)",
  "Tes": "Tes (rapper)",
  "Thanks For Coming": "Rachel Brown (musician)",
  "The Anchoress": "The Anchoress (musician)",
  "The Bill Holman Band": "Bill Holman (musician)",
  "The Caretaker": "The Caretaker (musician)",
  "The Classy Wrecks": "Elephant Man (musician)",
  "The Dare": "The Dare (musician)",
  "The Don Weller Big Band": "Don Weller (musician)",
  "The Field": "The Field (musician)",
  "The Gift Of Gab": "Gift of Gab (rapper)",
  "The Howard Roberts Quartet": "Howard Roberts (musician)",
  "The John Barry Orchestra": "John Barry (composer)",
  "The Martin Harley Band": "Martin Harley (musician)",
  "The Quantic Soul Orchestra": "Quantic (musician)",
  "The Rulers": "Josey Wales (singer)",
  "The Third Eye Foundation": "Matt Elliott (musician)",
  "The Toxic Avenger": "The Toxic Avenger (musician)",
  "Theodore Holland": "Theodore Holland (composer)",
  "Third Party": "Third Party (DJs)",
  "Thomas Albert": "Thomas Albert (composer)",
  "Thomas Attwood": "Thomas Attwood (composer)",
  "Thomas Ford": "Thomas Ford (composer)",
  "Thomas Gold": "Thomas Gold (DJ)",
  "Thomas Shaw": "Thomas Shaw (composer)",
  "Thomas Simpson": "Thomas Simpson (composer)",
  "Thundercat": "Thundercat (musician)",
  "Tia": "Tia (singer)",
  "Tiga": "Tiga (musician)",
  "Tiger": "Tiger (musician)",
  "Tilt": "Tilt (producers)",
  "Tim": "Tim (singer)",
  "Tim Burgess": "Tim Burgess (musician)",
  "Tim O'Brien": "Tim O'Brien (musician)",
  "Timbuktu": "Timbuktu (artist)",
  "Tina Charles": "Tina Charles (singer)",
  "Tiny Tim": "Tiny Tim (musician)",
  "Tirzah": "Tirzah (musician)",
  "Token": "Token (rapper)",
  "Tom Eaton": "Tom Eaton (musician)",
  "Tom Evans": "Tom Evans (musician)",
  "Tom Johnson": "Tom Johnson (composer)",
  "Tom Jones": "Tom Jones (singer)",
  "Tom Scott": "Tom Scott (saxophonist)",
  "Tommy Collins": "Tommy Collins (singer)",
  "Tommy Flanagan": "Tommy Flanagan (musician)",
  "Tommy Tucker": "Tommy Tucker (singer)",
  "Tony Allen": "Tony Allen (musician)",
  "Tony Banks": "Tony Banks (musician)",
  "Tony Clarke": "Tony Clarke (producer)",
  "Tony Martin": "Tony Martin (British singer)",
  "Tony Williams": "Tony Williams (drummer)",
  "Tormento": "Tormento (rapper)",
  "Tq": "TQ (singer)",
  "Tracy Nelson": "Tracy Nelson (singer)",
  "Transllusion": "James Stinson (musician)",
  "Trebor": "Trebor (composer)",
  "Trevor Daniel": "Trevor Daniel (singer)",
  "Tricky": "Tricky (rapper)",
  "Tsai Chin": "Tsai Chin (singer)",
  "Tua": "Tua (Rapper)",
  "Tweet": "Tweet (singer)",
  "Tyrone Brunson": "Tyrone Brunson (musician)",
  "Tyrone Washington": "Tyrone Washington (musician)",
  "UA": "Ua (singer)",
  "Ultimo": "Ultimo (singer)",
  "Untold": "Untold (musician)",
  "Upchurch": "Upchurch (musician)",
  "Urias": "Urias (singer)",
  "Uru": "Uru (singer)",
  "Usher": "Usher (musician)",
  "Ustad Sultan Khan": "Sultan Khan (musician)",
  "Vaccine": "Vaccine (musician)",
  "Valerie Smith": "Valerie Smith (musician)",
  "Vanessa Marquez": "Vanessa Marquez (singer)",
  "Vassy": "Vassy (singer)",
  "Vava": "Vava (rapper)",
  "Vector": "Vector (rapper)",
  "Venna": "Venna (musician)",
  "Vicco": "Vicco (singer)",
  "Vicky Chen": "Vicky Chen (singer)",
  "Victor Bailey": "Victor Bailey (musician)",
  "Victor Thompson": "Victor Thompson (musician)",
  "Vince Martin": "Vince Martin (singer)",
  "Vitamin C": "Vitamin C (singer)",
  "Vivian Jones": "Vivian Jones (singer)",
  "WC": "WC (rapper)",
  "Wale": "Wale (rapper)",
  "Walter Jackson": "Walter Jackson (singer)",
  "Warmduscher": "Warmduscher (DJ)",
  "Warren Hill": "Warren Hill (musician)",
  "Warrior King": "Warrior King (musician)",
  "Waveshaper": "Waveshaper (musician)",
  "Wayne Smith": "Wayne Smith (musician)",
  "Wendy": "Wendy (singer)",
  "Werner Kaegi": "Werner Kaegi (composer)",
  "Werner Müller Orchestra": "Werner Müller (musician)",
  "Whitey": "Whitey (musician)",
  "Whitney Rose": "Whitney Rose (musician)",
  "Wiley": "Wiley (musician)",
  "Wilkins": "Wilkins (singer)",
  "Will Holland": "Quantic (musician)",
  "Will Johnson": "Will Johnson (musician)",
  "William Beckett": "William Beckett (singer)",
  "William Bell": "William Bell (singer)",
  "William Clarke": "William Clarke (musician)",
  "William Corbett": "William Corbett (composer)",
  "William Doyle": "William Doyle (musician)",
  "William Duckworth": "William Duckworth (composer)",
  "William Fitzsimmons": "William Fitzsimmons (musician)",
  "William McDowell": "William McDowell (musician)",
  "William Mundy": "William Mundy (composer)",
  "William Parker": "William Parker (musician)",
  "William Ross": "William Ross (composer)",
  "William Tyler": "William Tyler (musician)",
  "Willie Brown": "Willie Brown (musician)",
  "Willie Jones": "Willie Jones (drummer)",
  "Willie Mitchell": "Willie Mitchell (musician)",
  "Willie Watson": "Willie Watson (musician)",
  "Willie Wright": "Willie Wright (musician)",
  "Willis Jackson": "Willis Jackson (saxophonist)",
  "Winny": "Winny (singer)",
  "Wise": "Wise (rapper)",
  "Wobbly": "Wobbly (musician)",
  "Wookie": "Wookie (musician)",
  "Wynter Gordon": "Diana Gordon (singer)",
  "Władysław Żeleński": "Władysław Żeleński (musician)",
  "XOV": "XOV (musician)",
  "Xamã": "Xamã (rapper)",
  "Xana": "Xana (musician)",
  "Xela": "Xela (musician)",
  "Xenia": "Xenia (singer)",
  "Xin Liu": "Liu Yuxin (singer)",
  "YC": "YC (rapper)",
  "YUI": "Yui (singer)",
  "Yellow Claw": "Yellow Claw (DJs)",
  "Yeri": "Yeri (singer)",
  "Yoji Biomehanika": "Yoji (DJ)",
  "YooJung": "Choi Yoo-jung (singer)",
  "Yuuri": "Yuuri (singer-songwriter)",
  "Yves": "Yves (singer)",
  "Yves Robert": "Yves Robert (musician)",
  "ZHU": "Zhu (musician)",
  "Zakir Hussain": "Zakir Hussain (musician)",
  "Zarif": "Zarif (singer)",
  "Zaz": "Zaz (singer)",
  "Zhang Hao": "Zhang Hao (singer)",
  "Zircon": "Zircon (composer)",
  "Zlatan": "Zlatan (musician)",
  "Zombie Nation": "Zombie Nation (musician)",
  "Zyon": "Germ (Rapper)",
  "cynthia.": "Cynthia (singer)",
  "d'Eon": "D'Eon (musician)",
  "felicita": "Felicita (musician)",
  "frnd": "Andrew Goldstein (musician)",
  "gonzalez": "José González (singer)",
  "i_o": "I o (musician)",
  "keshi": "Keshi (singer)",
  "lvl": "LVL (musician)",
  "miggy+": "Miggy (singer)",
  "miwa": "Miwa (singer)",
  "mpumi": "Mpumi (singer)",
  "osquinn": "Quinn (musician)",
  "patten": "Patten (musician)",
  "perto": "Perto (musician)",
  "teni": "Teni (singer)",
  "tuki.": "Tuki (singer)",
  "underscores": "Underscores (musician)",
  "ásdís": "Ásdís (singer)",
  "Бьянка": "Bianka (singer)",
  "Валентина Пономарёва": "Valentina Ponomaryova (singer)",
  "Дельфин": "Dolphin (musician)",
  "ЛСП": "LSP (rapper)",
  "НАТ'о": "N.A.T.o. (singer)",
  "Сона": "Sona (singer)",
  "Хаски": "Husky (rapper)",
  "Эндрю Хилл": "Andrew Hill (musician)",
  "いしだあゆみ": "Ayumi Ishida (singer)",
  "かめりあ": "Camellia (musician)",
  "さユり": "Sayuri (musician)",
  "ハナエ": "Hanae (singer)",
  "丁噹": "Ding Dang (singer)",
  "亜咲花": "Asaka (musician)",
  "今井美樹": "Miki Imai (singer)",
  "佐藤博": "Hiroshi Sato (musician)",
  "光良": "Michael Wong (singer)",
  "刀郎": "Dao Lang (singer)",
  "刘宇": "Liu Yu (singer)",
  "吳卓源": "Julia Wu (singer)",
  "品冠": "Victor Wong (singer)",
  "安藤裕子": "Yuko Ando (singer)",
  "小宇": "Xiao Yu (singer)",
  "小林泉美": "Izumi Kobayashi (musician)",
  "张信哲": "Jeff Chang (singer)",
  "张钰琪": "Zhang Yuqi (singer)",
  "彩音": "Ayane (singer)",
  "方力申": "Alex Fong (singer)",
  "李健": "Li Jian (singer)",
  "李圣杰": "Sam Lee (singer)",
  "李宗盛": "Jonathan Lee (musician)",
  "李艺彤": "Li Yitong (singer)",
  "李鑫一": "Li Xinyi (singer)",
  "林志美": "Samantha Lam (singer)",
  "汪峰": "Wang Feng (singer)",
  "潘裕文": "Peter Pan (singer)",
  "王霏霏": "Fei (singer)",
  "美波": "Minami (singer)",
  "詩音": "Shion (singer)",
  "许嵩": "Xu Song (singer)",
  "许巍": "Xu Wei (musician)",
  "赵雷": "Zhao Lei (singer)",
  "金莎": "Kym (singer)",
  "阿桑": "A-Sun (singer)",
  "陈琳": "Chen Lin (singer)",
  "陳慧嫻": "Priscilla Chan (singer)",
  "陳柏宇": "Jason Chan (singer)",
  "陳粒": "Chen Li (singer)",
  "韩红": "Han Hong (singer)",
  "香香": "Xiang Xiang (singer)",
  "高橋優": "Yu Takahashi (singer-songwriter)",
  "高橋瞳": "Hitomi Takahashi (singer)",
  "黃明昊 (Justin Huang)": "Justin Huang (singer)",
  "黃貫中": "Paul Wong (musician)",
  "黒魔": "Chroma (musician)",
  "가인": "Gain (singer)",
  "김범수": "Kim Bum-soo (singer)",
  "김진표": "Kim Jin-pyo (musician)",
  "김태우": "Kim Tae-woo (singer)",
  "김현정": "Kim Hyun-jung (singer)",
  "바다": "Bada (singer)",
  "박정민": "Park Jung-min (singer)",
  "사무엘": "Samuel (singer)",
  "소리": "Sori (singer)",
  "소연": "Park So-yeon (singer)",
  "유빈": "Kim Yu-bin (musician)",
  "이소라": "Lee So-ra (singer)",
  "제시카": "Jessica (singer)",
  "지선": "Ji Sun (singer)",
  "지아": "Zia (singer)",
  "카코포니": "Cacophony (musician)",
  "하리": "Hari (singer)"
};
