// Generated by fetch_photos.py — do not edit by hand.
// Entry ids with a portrait in ./photos/<id>.jpg. The globe's country
// popout reads this to know whose faces it can float over a country.
export const PHOTO_IDS = [
  'ada-lovelace',
  'albert-einstein',
  'aretha-franklin',
  'barack-obama',
  'beyonce',
  'chaplin',
  'david-attenborough',
  'emmy-noether',
  'frank-lloyd-wright',
  'frida-kahlo',
  'greta',
  'jane-austen',
  'john-lennon',
  'julia-child',
  'katherine-johnson',
  'marie-curie',
  'martin-luther-king-jr',
  'meryl-streep',
  'michael-jordan',
  'okeeffe',
  'stephen-curry',
  'steve-jobs',
  'taylor-swift',
  'toni-morrison',
  'turing',
];

export const HAS_PHOTO = new Set(PHOTO_IDS);
